package sp1fri

import (
	"bytes"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

// fixturePath resolves the runar repo's KoalaBear FRI fixture relative to
// this source file. The fixture is generated by /tmp/runar-fixture-gen
// (see tests/vectors/sp1/fri/minimal-guest/README.md for the regen
// command).
func fixturePath(t *testing.T) string {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	// thisFile = .../packages/runar-go/sp1fri/proof_test.go
	repo := filepath.Dir(filepath.Dir(filepath.Dir(filepath.Dir(thisFile))))
	return filepath.Join(repo, "tests", "vectors", "sp1", "fri", "minimal-guest", "proof.postcard")
}

// TestDecodeProofRoundTrip asserts the postcard decoder + encoder are
// byte-exact inverses against the real Plonky3 fixture. This validates
// the type tree shape (Proof / Commitments / OpenedValues / FriProof /
// QueryProof / BatchOpening / CommitPhaseProofStep), all field counts
// (digest=8, ext4=4), and varint encoding without depending on a Rust
// postcard binding.
func TestDecodeProofRoundTrip(t *testing.T) {
	bs, err := os.ReadFile(fixturePath(t))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}

	proof, err := DecodeProof(bs)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}

	t.Logf("decoded:")
	t.Logf("  degree_bits = %d", proof.DegreeBits)
	t.Logf("  commitments.trace cap_len = %d", len(proof.Commitments.Trace))
	if len(proof.Commitments.Trace) > 0 {
		t.Logf("  commitments.trace[0] = %v (canonical)", CanonicalDigest(proof.Commitments.Trace[0]))
	}
	t.Logf("  commitments.quotient_chunks cap_len = %d", len(proof.Commitments.QuotientChunks))
	t.Logf("  commitments.random present = %v", proof.Commitments.Random != nil)
	t.Logf("  opened_values.trace_local len = %d", len(proof.OpenedValues.TraceLocal))
	if proof.OpenedValues.TraceNext != nil {
		t.Logf("  opened_values.trace_next len = %d", len(*proof.OpenedValues.TraceNext))
	}
	t.Logf("  opened_values.quotient_chunks outer = %d", len(proof.OpenedValues.QuotientChunks))
	t.Logf("  fri.commit_phase_commits = %d", len(proof.OpeningProof.CommitPhaseCommits))
	t.Logf("  fri.commit_pow_witnesses = %d", len(proof.OpeningProof.CommitPowWitnesses))
	t.Logf("  fri.query_proofs = %d", len(proof.OpeningProof.QueryProofs))
	t.Logf("  fri.final_poly len = %d", len(proof.OpeningProof.FinalPoly))

	// Re-encode and assert byte-identical.
	out, err := EncodeProof(proof)
	if err != nil {
		t.Fatalf("encode: %v", err)
	}
	if !bytes.Equal(bs, out) {
		// Pinpoint first difference for easier debugging.
		minLen := len(bs)
		if len(out) < minLen {
			minLen = len(out)
		}
		var diff int
		for diff = 0; diff < minLen; diff++ {
			if bs[diff] != out[diff] {
				break
			}
		}
		t.Fatalf("encode roundtrip mismatch: input=%d bytes output=%d bytes; first diff at offset %d (input=0x%02x output=0x%02x)",
			len(bs), len(out), diff, bs[diff], out[diff])
	}
}

// TestProofConfigSanity asserts the decoded proof matches the config we
// pinned for `tests/vectors/sp1/fri/minimal-guest/`: Fibonacci AIR, 8-row
// trace, num_queries=2, log_blowup=2, log_final_poly_len=2, max_log_arity=1.
func TestProofConfigSanity(t *testing.T) {
	bs, err := os.ReadFile(fixturePath(t))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	proof, err := DecodeProof(bs)
	if err != nil {
		t.Fatalf("decode: %v", err)
	}

	// degree_bits = log2(8 trace rows) = 3
	if proof.DegreeBits != 3 {
		t.Errorf("degree_bits: want 3, got %d", proof.DegreeBits)
	}
	// FibonacciAir has 2 columns -> trace_local has 2 entries (Ext4 each)
	if got := len(proof.OpenedValues.TraceLocal); got != 2 {
		t.Errorf("trace_local len: want 2 (Fib has 2 cols), got %d", got)
	}
	// FibonacciAir uses next-row constraints
	if proof.OpenedValues.TraceNext == nil {
		t.Errorf("trace_next: want Some (Fib uses transition constraints), got None")
	}
	// num_queries = 2 -> 2 query proofs
	if got := len(proof.OpeningProof.QueryProofs); got != 2 {
		t.Errorf("query_proofs: want 2, got %d", got)
	}
	// final_poly length = 2^log_final_poly_len = 2^2 = 4 Ext4 coefficients
	if got := len(proof.OpeningProof.FinalPoly); got != 4 {
		t.Errorf("final_poly len: want 4 (2^log_final_poly_len=2), got %d", got)
	}
	// commit_phase_commits length = number of fold steps
	// log_height_after_blowup = degree_bits + log_blowup = 3 + 2 = 5
	// fold steps = log_height - log_final_poly_len - log_blowup = 5 - 2 - 2 = 1
	// (or: log_max_height - log_final_poly_len - log_blowup; depends on Plonky3 conventions)
	if got := len(proof.OpeningProof.CommitPhaseCommits); got < 1 {
		t.Errorf("commit_phase_commits: expected at least 1 fold-step commit, got %d", got)
	}
}
