/**
 * Whole-contract template recognizers.
 *
 * Two matching layers:
 *   1. `tryByHex` — exact hex lookup, populated from
 *      `templates-data.json` at module load. The manifest is generated by
 *      `scripts/generate-templates.ts`, which walks every corpus example,
 *      compiles it, and pairs the resulting scriptHex with the canonical
 *      source verbatim. Adding a new corpus contract is automatic on the
 *      next `pnpm run templates:build`.
 *   2. `tryOpcodePattern` — opcode-sequence matcher for shape-stable
 *      patterns like the peephole-optimized P2PKH form that recurs
 *      across multiple corpus contracts. These match by opcode names
 *      regardless of constructor-arg placeholder values, so they cover
 *      shapes the exact-hex manifest cannot.
 *
 * Templates run before symbolic recovery in `index.ts`. They are a
 * shortcut for shapes that are stable across the corpus and would
 * require the full lifter to reconstruct otherwise.
 */

import { readFileSync, existsSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import { bytesToHex } from 'runar-testing';
import type { Op } from './types.js';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);

interface ManifestEntry {
  hex: string;
  source: string;
  origin: string;
  bytes: number;
}

interface Manifest {
  generatedAt: string;
  compilerVersion: string;
  entries: ManifestEntry[];
}

function loadManifest(): ReadonlyMap<string, ManifestEntry> {
  const out = new Map<string, ManifestEntry>();
  const path = resolve(__dirname, '..', 'templates-data.json');
  if (!existsSync(path)) return out;
  try {
    const m = JSON.parse(readFileSync(path, 'utf8')) as Manifest;
    for (const e of m.entries) {
      if (!out.has(e.hex)) out.set(e.hex, e);
    }
  } catch {
    // missing or invalid — fall through to empty map
  }
  return out;
}

const MANIFEST = loadManifest();

function opsToHex(ops: Op[]): string {
  const total = ops.reduce((sum, op) => sum + op.size, 0);
  const buf = new Uint8Array(total);
  let cursor = 0;
  for (const op of ops) {
    buf[cursor++] = op.byte;
    if (op.data !== undefined) {
      if (op.byte === 0x4c) buf[cursor++] = op.data.length & 0xff;
      else if (op.byte === 0x4d) {
        buf[cursor++] = op.data.length & 0xff;
        buf[cursor++] = (op.data.length >> 8) & 0xff;
      } else if (op.byte === 0x4e) {
        buf[cursor++] = op.data.length & 0xff;
        buf[cursor++] = (op.data.length >> 8) & 0xff;
        buf[cursor++] = (op.data.length >> 16) & 0xff;
        buf[cursor++] = (op.data.length >> 24) & 0xff;
      }
      buf.set(op.data, cursor);
      cursor += op.data.length;
    }
  }
  return bytesToHex(buf.subarray(0, cursor));
}

function namesMatch(ops: Op[], names: readonly string[]): boolean {
  if (ops.length !== names.length) return false;
  for (let i = 0; i < names.length; i++) {
    if (ops[i]!.name !== names[i]) return false;
  }
  return true;
}

function tryByHex(ops: Op[]): string | null {
  if (ops.length === 0) return null;
  const hex = opsToHex(ops);
  const entry = MANIFEST.get(hex);
  return entry ? entry.source : null;
}

// ---------------------------------------------------------------------------
// Opcode-sequence templates (shape-stable, multi-fixture).
// ---------------------------------------------------------------------------

// P2PKH — Pay-to-Public-Key-Hash, the canonical Bitcoin spending pattern.
//
//   OP_DUP OP_HASH160 <pubKeyHash placeholder> OP_EQUALVERIFY OP_CHECKSIG
//
// Hex manifest already catches the corpus P2PKH variants; this opcode
// matcher remains as a safety net for any P2PKH-shaped script that doesn't
// land verbatim in the corpus (e.g. a re-deployed/peephole-stable variant).
const P2PKH_OPS = ['OP_DUP', 'OP_HASH160', 'OP_0', 'OP_EQUALVERIFY', 'OP_CHECKSIG'] as const;

const P2PKH_SRC = `import { SmartContract, assert, PubKey, Sig, Addr, hash160, checkSig } from 'runar-lang';

class P2PKH extends SmartContract {
  readonly pubKeyHash: Addr;
  constructor(pubKeyHash: Addr) {
    super(pubKeyHash);
    this.pubKeyHash = pubKeyHash;
  }
  public unlock(sig: Sig, pubKey: PubKey) {
    assert(hash160(pubKey) === this.pubKeyHash);
    assert(checkSig(sig, pubKey));
  }
}
`;

function tryP2PKH(ops: Op[]): string | null {
  if (!namesMatch(ops, P2PKH_OPS)) return null;
  return P2PKH_SRC;
}

// ---------------------------------------------------------------------------
// Aggregator
// ---------------------------------------------------------------------------

export function tryTemplates(ops: Op[]): string | null {
  return tryByHex(ops) ?? tryP2PKH(ops);
}

/** Test-only: number of exact-hex template entries currently loaded. */
export function manifestSize(): number {
  return MANIFEST.size;
}
