import { describe, it, expect } from 'vitest';
import { compile } from '../index.js';

// ---------------------------------------------------------------------------
// Contract sources
// ---------------------------------------------------------------------------

const P2PKH_SOURCE = `
class P2PKH extends SmartContract {
  readonly pk: PubKey;

  constructor(pk: PubKey) {
    super(pk);
    this.pk = pk;
  }

  public unlock(sig: Sig) {
    assert(checkSig(sig, this.pk));
  }
}
`;

const HASH_LOCK_SOURCE = `
class HashLock extends SmartContract {
  readonly hashValue: Sha256;

  constructor(hashValue: Sha256) {
    super(hashValue);
    this.hashValue = hashValue;
  }

  public unlock(preimage: ByteString) {
    assert(sha256(preimage) === this.hashValue);
  }
}
`;

const ESCROW_SOURCE = `
class Escrow extends SmartContract {
  readonly buyer: PubKey;
  readonly seller: PubKey;

  constructor(buyer: PubKey, seller: PubKey) {
    super(buyer, seller);
    this.buyer = buyer;
    this.seller = seller;
  }

  public release(sig: Sig) {
    assert(checkSig(sig, this.buyer));
  }

  public refund(sig: Sig) {
    assert(checkSig(sig, this.seller));
  }
}
`;

const IF_ELSE_SOURCE = `
class Conditional extends SmartContract {
  readonly threshold: bigint;

  constructor(threshold: bigint) {
    super(threshold);
    this.threshold = threshold;
  }

  public check(value: bigint) {
    if (value > this.threshold) {
      assert(value > 0n);
    } else {
      assert(value === 0n);
    }
  }
}
`;

const PRIVATE_METHOD_SOURCE = `
class WithHelper extends SmartContract {
  readonly owner: PubKey;

  constructor(owner: PubKey) {
    super(owner);
    this.owner = owner;
  }

  private requireOwner(sig: Sig) {
    assert(checkSig(sig, this.owner));
  }

  public spend(sig: Sig) {
    this.requireOwner(sig);
    assert(true);
  }
}
`;

const LOOP_SOURCE = `
class Summer extends SmartContract {
  readonly expected: bigint;

  constructor(expected: bigint) {
    super(expected);
    this.expected = expected;
  }

  public verify(start: bigint) {
    let sum: bigint = 0n;
    for (let i = 0n; i < 3n; i++) {
      sum = sum + start + i;
    }
    assert(sum === this.expected);
  }
}
`;

const COUNTER_SOURCE = `
class Counter extends StatefulSmartContract {
  count: bigint;

  constructor(count: bigint) {
    super(count);
    this.count = count;
  }

  public increment() {
    this.count++;
  }
}
`;

const MESSAGE_BOARD_SOURCE = `
class MessageBoard extends StatefulSmartContract {
  message: ByteString;
  readonly owner: PubKey;

  constructor(message: ByteString, owner: PubKey) {
    super(message, owner);
    this.message = message;
    this.owner = owner;
  }

  public post(newMessage: ByteString) {
    this.message = newMessage;
  }

  public burn(sig: Sig) {
    assert(checkSig(sig, this.owner));
  }
}
`;

const INITIALIZER_SOURCE = `
class WithDefault extends SmartContract {
  readonly limit: bigint = 100n;
  readonly pk: PubKey;

  constructor(pk: PubKey) {
    super(pk);
    this.pk = pk;
  }

  public check(value: bigint) {
    assert(value <= this.limit);
    assert(checkSig(toByteString('00'), this.pk));
  }
}
`;

// ---------------------------------------------------------------------------
// Tests
// ---------------------------------------------------------------------------

describe('Pass 7: SX Emit', () => {

  describe('emitSX option', () => {
    it('does not produce SX by default', () => {
      const result = compile(P2PKH_SOURCE);
      expect(result.sx).toBeUndefined();
    });

    it('produces SX when emitSX is true', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
      expect(typeof result.sx).toBe('string');
      expect(result.sx!.length).toBeGreaterThan(0);
    });

    it('attaches SX to artifact', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      expect(result.artifact).toBeDefined();
      expect(result.artifact!.sx).toBeDefined();
      expect(result.artifact!.sx).toBe(result.sx);
    });

    it('still produces hex output alongside SX', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      expect(result.scriptHex).toBeDefined();
      expect(result.scriptAsm).toBeDefined();
    });
  });

  describe('P2PKH — stateless, single method, property placeholder', () => {
    it('includes contract header', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      expect(result.sx).toContain('P2PKH.sx');
      expect(result.sx).toContain('generated by Runar');
    });

    it('includes constructor variable for pk', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      expect(result.sx).toContain('.pk');
    });

    it('uses SX camelCase opcodes', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      // P2PKH should contain checkSig
      expect(result.sx).toContain('checkSig');
    });

    it('does not contain OP_ prefixed names', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      // SX output should use camelCase, not OP_ prefix
      expect(result.sx).not.toMatch(/OP_[A-Z]/);
    });

    it('does not contain hex-encoded opcodes', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      // SX output should be text, not hex
      expect(result.sx).not.toMatch(/^[0-9a-f]{4,}$/m);
    });
  });

  describe('HashLock — builtin call (sha256) + equality check', () => {
    it('compiles with SX', () => {
      const result = compile(HASH_LOCK_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('contains sha256 opcode', () => {
      const result = compile(HASH_LOCK_SOURCE, { emitSX: true });
      expect(result.sx).toContain('sha256');
    });

    it('contains .hashValue variable', () => {
      const result = compile(HASH_LOCK_SOURCE, { emitSX: true });
      expect(result.sx).toContain('.hashValue');
    });

    it('contains equal (bytes comparison)', () => {
      const result = compile(HASH_LOCK_SOURCE, { emitSX: true });
      // sha256 result compared with === on ByteString types → OP_EQUAL
      expect(result.sx).toContain('equal');
    });
  });

  describe('Escrow — multi-method dispatch', () => {
    it('compiles with SX', () => {
      const result = compile(ESCROW_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('contains dispatch structure', () => {
      const result = compile(ESCROW_SOURCE, { emitSX: true });
      // Multi-method → if/else dispatch
      expect(result.sx).toContain('numEqual');
      expect(result.sx).toContain('if');
      expect(result.sx).toContain('else');
      expect(result.sx).toContain('endIf');
    });

    it('contains both method comments', () => {
      const result = compile(ESCROW_SOURCE, { emitSX: true });
      expect(result.sx).toContain('release');
      expect(result.sx).toContain('refund');
    });

    it('contains .buyer and .seller variables', () => {
      const result = compile(ESCROW_SOURCE, { emitSX: true });
      expect(result.sx).toContain('.buyer');
      expect(result.sx).toContain('.seller');
    });
  });

  describe('If/else — conditional branches', () => {
    it('compiles with SX', () => {
      const result = compile(IF_ELSE_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('contains if/else/endIf', () => {
      const result = compile(IF_ELSE_SOURCE, { emitSX: true });
      expect(result.sx).toContain('if');
      expect(result.sx).toContain('else');
      expect(result.sx).toContain('endIf');
    });

    it('contains .threshold variable', () => {
      const result = compile(IF_ELSE_SOURCE, { emitSX: true });
      expect(result.sx).toContain('.threshold');
    });
  });

  describe('Private methods — macros', () => {
    it('compiles with SX', () => {
      const result = compile(PRIVATE_METHOD_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('contains #macro definition for private method', () => {
      const result = compile(PRIVATE_METHOD_SOURCE, { emitSX: true });
      expect(result.sx).toContain('#requireOwner');
      expect(result.sx).toMatch(/#requireOwner[\s\S]*?end/);
    });

    it('contains macro call in public method body', () => {
      const result = compile(PRIVATE_METHOD_SOURCE, { emitSX: true });
      // The macro should be called by bare name in the public method
      const lines = result.sx!.split('\n');
      const macroDefLine = lines.findIndex(l => l.includes('#requireOwner'));
      const endLine = lines.findIndex((l, i) => i > macroDefLine && l.trim() === 'end');
      // After the macro definition, the public method body should call it
      const afterMacro = lines.slice(endLine + 1);
      const callLine = afterMacro.find(l => l.trim() === 'requireOwner');
      expect(callLine).toBeDefined();
    });

    it('macro contains checkSig and .owner', () => {
      const result = compile(PRIVATE_METHOD_SOURCE, { emitSX: true });
      // Extract macro body
      const match = result.sx!.match(/#requireOwner([\s\S]*?)end/);
      expect(match).not.toBeNull();
      const macroBody = match![1]!;
      expect(macroBody).toContain('checkSig');
      expect(macroBody).toContain('.owner');
    });
  });

  describe('Bounded loop — repeat', () => {
    it('compiles with SX', () => {
      const result = compile(LOOP_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('contains repeat ... end block', () => {
      const result = compile(LOOP_SOURCE, { emitSX: true });
      expect(result.sx).toContain('repeat 3n');
      expect(result.sx).toContain('end');
    });

    it('does not unroll the loop', () => {
      const result = compile(LOOP_SOURCE, { emitSX: true });
      // Should have exactly one repeat block, not 3 copies of the body
      const repeatCount = (result.sx!.match(/repeat/g) || []).length;
      expect(repeatCount).toBe(1);
    });

    it('contains .expected variable', () => {
      const result = compile(LOOP_SOURCE, { emitSX: true });
      expect(result.sx).toContain('.expected');
    });
  });

  describe('Property initializers', () => {
    it('compiles with SX', () => {
      const result = compile(INITIALIZER_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('uses literal value for initialized property', () => {
      const result = compile(INITIALIZER_SOURCE, { emitSX: true });
      // limit = 100n should appear as a literal, not as .limit variable
      expect(result.sx).toContain('100n');
    });

    it('uses .variable for non-initialized property', () => {
      const result = compile(INITIALIZER_SOURCE, { emitSX: true });
      expect(result.sx).toContain('.pk');
    });
  });

  describe('Counter — stateful contract', () => {
    it('compiles with SX', () => {
      const result = compile(COUNTER_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('contains codeSeparator for checkPreimage', () => {
      const result = compile(COUNTER_SOURCE, { emitSX: true });
      expect(result.sx).toContain('codeSeparator');
    });

    it('contains checkSigVerify for OP_PUSH_TX', () => {
      const result = compile(COUNTER_SOURCE, { emitSX: true });
      expect(result.sx).toContain('checkSigVerify');
    });

    it('contains generator point G', () => {
      const result = compile(COUNTER_SOURCE, { emitSX: true });
      // Compressed secp256k1 generator
      expect(result.sx).toContain('0279be667ef9dcbbac55a06295ce870b07029bfcdb2dce28d959f2815b16f81798');
    });

    it('contains state deserialization opcodes', () => {
      const result = compile(COUNTER_SOURCE, { emitSX: true });
      // State extraction splits at 104 bytes (BIP-143 header)
      expect(result.sx).toContain('104n');
      expect(result.sx).toContain('split');
      expect(result.sx).toContain('bin2num');
    });

    it('contains hash256 for output verification', () => {
      const result = compile(COUNTER_SOURCE, { emitSX: true });
      expect(result.sx).toContain('hash256');
    });
  });

  describe('MessageBoard — stateful with readonly + mutable', () => {
    it('compiles with SX', () => {
      const result = compile(MESSAGE_BOARD_SOURCE, { emitSX: true });
      expect(result.success).toBe(true);
      expect(result.sx).toBeDefined();
    });

    it('contains dispatch for post and burn', () => {
      const result = compile(MESSAGE_BOARD_SOURCE, { emitSX: true });
      expect(result.sx).toContain('post');
      expect(result.sx).toContain('burn');
    });

    it('contains .owner for readonly property', () => {
      const result = compile(MESSAGE_BOARD_SOURCE, { emitSX: true });
      expect(result.sx).toContain('.owner');
    });
  });

  describe('SX output is readable', () => {
    it('P2PKH output snapshot', () => {
      const result = compile(P2PKH_SOURCE, { emitSX: true });
      // Print for manual inspection during development
      // console.log(result.sx);
      expect(result.sx).toBeDefined();
      // Each line should be a valid SX token or comment
      const lines = result.sx!.split('\n').filter(l => l.trim().length > 0);
      for (const line of lines) {
        const trimmed = line.trim();
        // Should be a comment, SX token, or structural keyword
        const isValid = trimmed.startsWith('//')
          || trimmed.startsWith('#')
          || trimmed.startsWith('.')
          || trimmed === 'end'
          || trimmed === 'if'
          || trimmed === 'else'
          || trimmed === 'endIf'
          || /^[a-z0-9]/.test(trimmed)
          || /^-?\d+n/.test(trimmed)
          || /^0x[0-9a-f]+/.test(trimmed)
          || trimmed === 'true'
          || trimmed === 'false';
        expect(isValid).toBe(true);
      }
    });
  });
});
