/**
 * R-186 / R-292 (CL-BUG-122, CL-GAP-087): `lowerLoop` drops the iteration
 * variable ONLY when it is exactly on top of the stack.
 *
 *     if (this.stackMap.has(_iterVar)) {
 *       const depth = this.stackMap.findDepth(_iterVar);
 *       if (depth === 0) { emit drop; pop; }
 *     }
 *
 * The reviewers filed it twice — against the TypeScript reference (CL-BUG-122)
 * and against the Rust twin (CL-GAP-087). All seven tiers spell the same
 * `depth === 0` guard, so all seven leak identically and cross-tier parity sees
 * nothing.
 *
 * WHEN THE GUARD HOLDS: the body's last binding consumes its own operands — an
 * assert-only body, or a body that reads the iteration variable last.
 *
 * WHEN IT DOES NOT: the body's last binding LEAVES a value. The plainest case is
 * the accumulator every loop is written for:
 *
 *     for (let k = 0n; k < N; k++) { sum = sum + x; }
 *
 * `sum` is rebound in place and ends on top, so the iteration variable sits at
 * depth 1 and is never dropped. Measured on the TypeScript reference, the stack
 * map after three iterations reads
 *
 *     ["y", "i", "i", "i", "carried"]
 *
 * — one leaked slot per iteration, and `maxStackDepth` grows as `3 + N`.
 *
 * It is NOT a wrong-answer bug: the stack model tracks the leaked slots, so
 * every later read still resolves, and the public-method epilogue
 * (`cleanupExcessStack`) nips the residue before the script ends, so the
 * consensus clean-stack rule is satisfied. The cost is a wasted stack item and
 * a wasted OP_NIP per iteration — until the count is large enough that the
 * leak alone crosses the compiler's own 800-item bound and a valid contract is
 * REFUSED. Measured, for the accumulator below: 797 iterations compiles at a
 * modelled depth of exactly 800, and
 *
 *     798 iterations → "exceeds maximum stack depth of 800 (actual: 801)"
 *
 * where the same contract needs a working set of three. A body that also binds
 * an unused local leaks two per iteration and is refused from 398.
 *
 * This is not a synthetic shape. `conformance/fuzz-regressions/entries/
 * 2026-08-06-branch-k1-empty-pad-guard-bypass/contract.runar.ts` — checked in,
 * generated by the fuzzer, not written for this test — leaks in both of its
 * loop-bearing methods.
 *
 * The assertion below is the one that states the property rather than the
 * symptom: a loop's stack cost must not scale with its iteration count. The
 * cross-tier case pins that all seven fix it the same way, because a tier that
 * cleaned up differently would move bytes.
 */

import { describe, it, expect } from 'vitest';
import { spawnSync } from 'node:child_process';
import { mkdtempSync, writeFileSync, existsSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { compile, lowerToStack } from 'runar-compiler';
import {
  findGoBinary,
  findRustBinary,
  findPythonBinary,
  findZigBinary,
  findRubyBinary,
  findJavaBinary,
} from '../conformance/runner/runner.js';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/**
 * `sum = sum + this.step` is the last statement, so the loop body ends with the
 * accumulator on top and the iteration variable beneath it. Nothing else in the
 * contract touches the stack during the loop.
 */
function accumulator(iterations: number): string {
  return `
import { SmartContract, assert } from 'runar-lang';

class LoopTail extends SmartContract {
  readonly step: bigint;

  constructor(step: bigint) {
    super(step);
    this.step = step;
  }

  public unlock(seed: bigint): void {
    let sum: bigint = seed;
    for (let k: bigint = 0n; k < ${iterations}n; k++) {
      sum = (sum + this.step);
    }
    assert(sum >= seed);
  }
}
`;
}

/** Past the 798-iteration threshold above, so the leak alone crosses the bound. */
const REFUSED_AT = 800;

function modelDepth(iterations: number): number {
  const res = compile(accumulator(iterations), {
    fileName: 'LoopTail.runar.ts',
    disableConstantFolding: true,
  });
  const program = lowerToStack(res.anf);
  const methods = (program as unknown as { methods?: unknown }).methods ?? program;
  const unlock = (methods as Array<{ name: string; maxStackDepth: number }>).find(
    (m) => m.name === 'unlock',
  );
  if (!unlock) throw new Error('no unlock method in the lowered program');
  return unlock.maxStackDepth;
}

function splitCmd(s: string | null): { cmd: string | null; args: string[] } {
  if (s === null) return { cmd: null, args: [] };
  const parts = s.trim().split(/\s+/);
  return { cmd: parts[0] ?? null, args: parts.slice(1) };
}

interface Tier {
  id: string;
  binary: string | null;
  cwd: string;
  /** Zig's fold flag does not exist; it never folds. */
  foldFlag: boolean;
}

const TIERS: Tier[] = [
  { id: 'go', binary: findGoBinary(), cwd: join(ROOT, 'compilers/go'), foldFlag: true },
  { id: 'rust', binary: findRustBinary(), cwd: join(ROOT, 'compilers/rust'), foldFlag: true },
  { id: 'python', binary: findPythonBinary(), cwd: join(ROOT, 'compilers/python'), foldFlag: true },
  { id: 'zig', binary: findZigBinary(), cwd: join(ROOT, 'compilers/zig'), foldFlag: true },
  { id: 'ruby', binary: findRubyBinary(), cwd: join(ROOT, 'compilers/ruby'), foldFlag: true },
  { id: 'java', binary: findJavaBinary(), cwd: join(ROOT, 'compilers/java'), foldFlag: true },
];

/** Compile `source` with one native tier and return its script hex. */
function nativeHex(tier: Tier, source: string): string {
  const { cmd, args } = splitCmd(tier.binary);
  const dir = mkdtempSync(join(tmpdir(), `r186-${tier.id}-`));
  try {
    const src = join(dir, 'LoopTail.runar.ts');
    writeFileSync(src, source);
    const argv = [...args, '--source', src, '--hex'];
    if (tier.foldFlag) argv.push('--disable-constant-folding');
    const res = spawnSync(cmd!, argv, {
      cwd: tier.cwd,
      encoding: 'utf-8',
      timeout: 300_000,
      maxBuffer: 64 * 1024 * 1024,
    });
    if (res.status !== 0) {
      throw new Error(
        `${tier.id} exited ${res.status}: ${(res.stderr || res.stdout || '').slice(0, 400)}`,
      );
    }
    // Zig interleaves allocator diagnostics with its output; the hex is line 1.
    const first = (res.stdout.split('\n')[0] ?? '').replace(/\s/g, '').toLowerCase();
    if (!/^[0-9a-f]+$/.test(first)) {
      throw new Error(`${tier.id} printed no hex: ${res.stdout.slice(0, 200)}`);
    }
    return first;
  } finally {
    rmSync(dir, { recursive: true, force: true });
  }
}

describe("R-186 / R-292: a loop's stack cost does not scale with its iteration count", () => {
  it('control: a body that reads the iteration variable LAST already cleans up', () => {
    // `sum = sum + k` consumes `k` at its last use, so the guard's `depth === 0`
    // holds and this shape was never affected. It pins that the fix does not
    // change the case that already worked.
    const readsIterLast = (n: number) => `
import { SmartContract, assert } from 'runar-lang';

class LoopIterLast extends SmartContract {
  readonly step: bigint;
  constructor(step: bigint) { super(step); this.step = step; }
  public unlock(seed: bigint): void {
    let sum: bigint = seed;
    for (let k: bigint = 0n; k < ${n}n; k++) {
      sum = (sum + k);
    }
    assert(sum >= seed);
  }
}
`;
    const depthOf = (n: number) => {
      const res = compile(readsIterLast(n), {
        fileName: 'LoopIterLast.runar.ts',
        disableConstantFolding: true,
      });
      const program = lowerToStack(res.anf);
      const methods = (program as unknown as { methods?: unknown }).methods ?? program;
      return (methods as Array<{ name: string; maxStackDepth: number }>).find(
        (m) => m.name === 'unlock',
      )!.maxStackDepth;
    };
    expect(depthOf(50)).toBe(depthOf(10));
  });

  it('an accumulator loop costs the same stack at 10 iterations as at 50', () => {
    const ten = modelDepth(10);
    const fifty = modelDepth(50);
    expect(
      fifty,
      `the loop leaks ${(fifty - ten) / 40} stack item(s) per iteration: ` +
        `depth ${ten} at 10 iterations, ${fifty} at 50`,
    ).toBe(ten);
  });

  it(`a ${REFUSED_AT}-iteration accumulator loop is not refused for depth it does not use`, () => {
    expect(() => modelDepth(REFUSED_AT)).not.toThrow();
    expect(modelDepth(REFUSED_AT)).toBeLessThan(10);
  });

  describe('every tier cleans up the same way', () => {
    const available = TIERS.filter((t) => t.binary !== null && existsSync(t.cwd));

    it('at least two native tiers are built (a one-tier run proves nothing)', () => {
      expect(available.length).toBeGreaterThanOrEqual(2);
    });

    it(`all built tiers compile the ${REFUSED_AT}-iteration loop to identical bytes`, () => {
      const source = accumulator(REFUSED_AT);
      const ts = compile(source, {
        fileName: 'LoopTail.runar.ts',
        disableConstantFolding: true,
      });
      expect(ts.success, JSON.stringify(ts.diagnostics)).toBe(true);
      const byTier = new Map<string, string>([['ts', ts.scriptHex!.toLowerCase()]]);
      for (const tier of available) {
        byTier.set(tier.id, nativeHex(tier, source));
      }
      const distinct = new Map<string, string[]>();
      for (const [id, hex] of byTier) {
        const seen = distinct.get(hex) ?? [];
        seen.push(id);
        distinct.set(hex, seen);
      }
      expect(
        [...distinct.values()].map((ids) => ids.join('+')),
        'tiers disagreed on the compiled bytes',
      ).toEqual([[...byTier.keys()].join('+')]);
    }, 600_000);
  });
});
