/**
 * R-239 (CL-GAP-015): the EC domain parameters are pasted as literals with no
 * upstream-source citation, while less critical constants in the same packages
 * do cite theirs.
 *
 * `poseidon2_koalabear.go` names Plonky3 and links the file it was extracted
 * from; the SLH-DSA parameters cite FIPS 205. The secp256k1 field prime and
 * generator, the P-256 and P-384 parameters, and the BN254 field prime and
 * curve order are bare hex strings inside an `init()`.
 *
 * These are the constants where a typo is worst and review is hardest. A wrong
 * digit in a Poseidon2 round constant makes a test vector fail. A wrong digit in
 * a curve's field prime produces an EC implementation that agrees with itself,
 * passes every self-consistency check, and is not the curve anyone else is on —
 * and there is no vector in the repo to catch it, because the vectors would be
 * generated by the same wrong constant. The only defence is checking the digits
 * against the standard, which is only possible if the standard is named.
 *
 * The test does not check that constants are CORRECT — it cannot. It checks
 * that each one names where it came from, so that checking is possible at all.
 */

import { describe, it, expect } from 'vitest';
import { readFileSync, existsSync } from 'node:fs';
import { join, dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..');

/** Files that hold curve domain parameters, per the finding. */
const FILES = [
  'compilers/go/codegen/ec.go',
  'compilers/go/codegen/p256_p384.go',
  'compilers/go/codegen/bn254.go',
  'compilers/rust/src/codegen/p256_p384.rs',
];

/** A citation: a standard's name or a URL. */
const CITATION =
  /SEC 2|SEC2|FIPS 186|FIPS186|RFC ?\d{4}|NIST SP|EIP-?197|EIP-?196|Barreto|https?:\/\//i;

/** A 48+ hex-digit literal is a curve parameter, not an ordinary constant. */
const BIG_HEX = /"([0-9a-fA-F]{48,})"/g;

describe('R-239: curve domain parameters name their source', () => {
  it('the files are where the finding says', () => {
    for (const f of FILES) {
      expect(existsSync(join(ROOT, f)), `${f} moved`).toBe(true);
    }
  });

  it('the scan finds the constants it is about', () => {
    const total = FILES.reduce(
      (n, f) => n + [...readFileSync(join(ROOT, f), 'utf-8').matchAll(BIG_HEX)].length,
      0,
    );
    expect(total, 'no large hex literals found — the scan broke').toBeGreaterThan(5);
  });

  for (const f of FILES) {
    it(`${f} cites a standard for its curve parameters`, () => {
      const text = readFileSync(join(ROOT, f), 'utf-8');
      const hits = [...text.matchAll(BIG_HEX)];
      if (hits.length === 0) return;
      expect(
        CITATION.test(text),
        `${f} pastes ${hits.length} curve parameter literal(s) and names no ` +
          `standard or URL they can be checked against`,
      ).toBe(true);
    });
  }
});
