package runar

// Cross-tier interop test for the signed-envelope wire protocol. Reads the
// shared fixture at `conformance/sdk-envelope/fixtures.json` (generated by
// the TS reference impl) and asserts that:
//
//   1. CanonicalJSON produces byte-identical output for every documented input.
//   2. VerifyEnvelope returns OK=true for the valid envelope at verify_now_ms.
//   3. VerifyEnvelope returns the listed reason for every tampered envelope.
//
// Any failure here is a cross-tier protocol divergence. See CLAUDE.md §"Seven
// SDKs Must Stay in Sync" for the rationale.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

type fixtureCanonicalVector struct {
	Input    any    `json:"input"`
	Expected string `json:"expected"`
}

type fixtureRejection struct {
	Reason   string         `json:"reason"`
	Envelope SignedEnvelope `json:"envelope"`
}

type fixture struct {
	FixtureVersion       int                      `json:"fixture_version"`
	AlicePubHex          string                   `json:"alice_pub_hex"`
	Nonce                int64                    `json:"nonce"`
	ExpiresAt            int64                    `json:"expires_at"`
	VerifyNowMs          int64                    `json:"verify_now_ms"`
	CanonicalJSONVectors []fixtureCanonicalVector `json:"canonical_json_vectors"`
	ValidEnvelope        SignedEnvelope           `json:"valid_envelope"`
	RejectionVectors     []fixtureRejection       `json:"rejection_vectors"`
}

func loadFixture(t *testing.T) fixture {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(thisFile), "..", "..", "conformance", "sdk-envelope", "fixtures.json")
	bytes, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	dec := json.NewDecoder(stringReader(string(bytes)))
	dec.UseNumber()
	var raw map[string]any
	if err := dec.Decode(&raw); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}

	// Round-trip into our typed shape via re-encoding so json.Number-typed
	// nonce/expiresAt fields land in the right places.
	var f fixture
	if err := json.Unmarshal(bytes, &f); err != nil {
		t.Fatalf("unmarshal fixture: %v", err)
	}
	// Re-decode CanonicalJSONVectors with UseNumber semantics so the
	// inputs preserve int-vs-float intent identically to the JS source.
	cv := raw["canonical_json_vectors"].([]any)
	f.CanonicalJSONVectors = make([]fixtureCanonicalVector, len(cv))
	for i, e := range cv {
		obj := e.(map[string]any)
		f.CanonicalJSONVectors[i] = fixtureCanonicalVector{
			Input:    normalizeJSON(obj["input"]),
			Expected: obj["expected"].(string),
		}
	}
	return f
}

// normalizeJSON converts json.Number leaves into int64 (when exact) or float64
// so they match what the TS source value would have been. CanonicalJSON
// handles both, but the inputs need stable types per leaf.
func normalizeJSON(v any) any {
	switch x := v.(type) {
	case json.Number:
		if i, err := x.Int64(); err == nil {
			return i
		}
		f, _ := x.Float64()
		return f
	case map[string]any:
		out := make(map[string]any, len(x))
		for k, v := range x {
			out[k] = normalizeJSON(v)
		}
		return out
	case []any:
		out := make([]any, len(x))
		for i, v := range x {
			out[i] = normalizeJSON(v)
		}
		return out
	}
	return v
}

func TestEnvelopeInterop_CanonicalJSON(t *testing.T) {
	f := loadFixture(t)
	for i, v := range f.CanonicalJSONVectors {
		got, err := CanonicalJSON(v.Input)
		if err != nil {
			t.Errorf("vector %d: error %v", i, err)
			continue
		}
		if got != v.Expected {
			t.Errorf("vector %d:\n  got:  %s\n want:  %s", i, got, v.Expected)
		}
	}
}

func TestEnvelopeInterop_VerifyValid(t *testing.T) {
	f := loadFixture(t)
	r := VerifyEnvelope(VerifyEnvelopeOpts{
		Envelope: f.ValidEnvelope,
		NowMs:    f.VerifyNowMs,
	})
	if !r.OK {
		t.Fatalf("expected ok=true for valid_envelope; reason=%s", r.Reason)
	}
}

func TestEnvelopeInterop_RejectionVectors(t *testing.T) {
	f := loadFixture(t)
	for _, rv := range f.RejectionVectors {
		// The fixture's "expired" entry uses its own past expiresAt; verify
		// against verify_now_ms.
		r := VerifyEnvelope(VerifyEnvelopeOpts{
			Envelope: rv.Envelope,
			NowMs:    f.VerifyNowMs,
		})
		if r.OK {
			t.Errorf("rejection %q: expected ok=false", rv.Reason)
			continue
		}
		if string(r.Reason) != rv.Reason {
			t.Errorf("rejection %q: got reason=%s want=%s", rv.Reason, r.Reason, rv.Reason)
		}
	}
}

// TestEnvelopeInterop_CanonicalJSONRejectionVectors verifies that
// CanonicalJSON rejects inputs which RFC 8785 forbids. Per
// audits/canonical-json-rfc8785-parity.md §3 rec 6 (D6), the lone-surrogate
// case is the gating example. Each input is reconstructed from a UTF-16
// code-unit array so JSON-parser divergence (Go's encoding/json replaces lone
// surrogates with U+FFFD, Ruby errors at parse-time, etc.) does not mask the
// canonical_json behaviour we are gating.
func TestEnvelopeInterop_CanonicalJSONRejectionVectors(t *testing.T) {
	path := mustFixturePath(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var top map[string]any
	dec := json.NewDecoder(stringReader(string(raw)))
	dec.UseNumber()
	if err := dec.Decode(&top); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	rvs, _ := top["canonical_json_rejection_vectors"].([]any)
	if len(rvs) == 0 {
		t.Fatal("canonical_json_rejection_vectors missing or empty")
	}
	for _, raw := range rvs {
		v := raw.(map[string]any)
		id, _ := v["_vector_id"].(string)
		key, _ := v["input_object_key"].(string)
		units, _ := v["input_value_utf16_units"].([]any)
		// Build a Go string from UTF-16 units. Go strings are byte sequences;
		// utf16.Decode returns runes but a lone surrogate becomes
		// utf8.RuneError. We instead emit the surrogate as its WTF-8 / CESU-8
		// byte pattern so the canonical_json escaper sees the lone surrogate
		// rather than a replacement char.
		var bad []byte
		for _, u := range units {
			n, _ := u.(json.Number)
			cp, _ := n.Int64()
			// Encode lone surrogate as 3-byte UTF-8 of the surrogate value
			// itself (illegal but unambiguous; Go's range loop will yield
			// utf8.RuneError 0xFFFD on this).
			bad = append(bad, byte(0xe0|(cp>>12)), byte(0x80|((cp>>6)&0x3f)), byte(0x80|(cp&0x3f)))
		}
		input := map[string]any{key: string(bad)}
		got, err := CanonicalJSON(input)
		if err == nil {
			t.Errorf("vector %s: CanonicalJSON did NOT reject lone surrogate; got %s", id, got)
		}
	}
}

func mustFixturePath(t *testing.T) string {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "conformance", "sdk-envelope", "fixtures.json")
}
