package runar

// Cross-tier interop test for the signed-envelope wire protocol. Reads the
// shared fixture at `conformance/sdk-envelope/fixtures.json` (generated by
// the TS reference impl) and asserts that:
//
//   1. CanonicalJSON produces byte-identical output for every documented input.
//   2. VerifyEnvelope returns OK=true for the valid envelope at verify_now_ms.
//   3. VerifyEnvelope returns the listed reason for every tampered envelope.
//
// Any failure here is a cross-tier protocol divergence. See CLAUDE.md §"Seven
// SDKs Must Stay in Sync" for the rationale.

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"testing"
)

type fixtureCanonicalVector struct {
	Input    any    `json:"input"`
	Expected string `json:"expected"`
}

type fixtureRejection struct {
	Reason   string         `json:"reason"`
	Envelope SignedEnvelope `json:"envelope"`
}

type fixtureDepthVector struct {
	VectorID string         `json:"_vector_id"`
	MaxDepth int            `json:"max_depth"`
	ExpectOK bool           `json:"expect_ok"`
	Reason   string         `json:"reason"`
	Envelope SignedEnvelope `json:"envelope"`
}

type fixtureClockVector struct {
	VectorID string `json:"_vector_id"`
	// Pointers so a JSON null ("the caller supplies nothing") is
	// distinguishable from an explicit 0 — which is the whole point of the
	// vector set.
	ClockSkewMs *int64 `json:"clock_skew_ms"`
	NowMs       *int64 `json:"now_ms"`
	ExpectOK    bool   `json:"expect_ok"`
	Reason      string `json:"reason"`
}

type fixture struct {
	FixtureVersion       int                      `json:"fixture_version"`
	AlicePubHex          string                   `json:"alice_pub_hex"`
	Nonce                int64                    `json:"nonce"`
	ExpiresAt            int64                    `json:"expires_at"`
	VerifyNowMs          int64                    `json:"verify_now_ms"`
	CanonicalJSONVectors []fixtureCanonicalVector `json:"canonical_json_vectors"`
	ValidEnvelope        SignedEnvelope           `json:"valid_envelope"`
	RejectionVectors     []fixtureRejection       `json:"rejection_vectors"`
	PayloadDepthLimit    int                      `json:"payload_depth_limit"`
	ClockSkewVectors     []fixtureClockVector     `json:"clock_skew_vectors"`
	DepthVectors         []fixtureDepthVector     `json:"depth_vectors"`
}

func loadFixture(t *testing.T) fixture {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(thisFile), "..", "..", "conformance", "sdk-envelope", "fixtures.json")
	bytes, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	dec := json.NewDecoder(stringReader(string(bytes)))
	dec.UseNumber()
	var raw map[string]any
	if err := dec.Decode(&raw); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}

	// Round-trip into our typed shape via re-encoding so json.Number-typed
	// nonce/expiresAt fields land in the right places.
	var f fixture
	if err := json.Unmarshal(bytes, &f); err != nil {
		t.Fatalf("unmarshal fixture: %v", err)
	}
	// Re-decode CanonicalJSONVectors with UseNumber semantics so the
	// inputs preserve int-vs-float intent identically to the JS source.
	cv := raw["canonical_json_vectors"].([]any)
	f.CanonicalJSONVectors = make([]fixtureCanonicalVector, len(cv))
	for i, e := range cv {
		obj := e.(map[string]any)
		f.CanonicalJSONVectors[i] = fixtureCanonicalVector{
			Input:    normalizeJSON(obj["input"]),
			Expected: obj["expected"].(string),
		}
	}
	return f
}

// normalizeJSON converts json.Number leaves into int64 (when exact) or float64
// so they match what the TS source value would have been. CanonicalJSON
// handles both, but the inputs need stable types per leaf.
func normalizeJSON(v any) any {
	switch x := v.(type) {
	case json.Number:
		if i, err := x.Int64(); err == nil {
			return i
		}
		f, _ := x.Float64()
		return f
	case map[string]any:
		out := make(map[string]any, len(x))
		for k, v := range x {
			out[k] = normalizeJSON(v)
		}
		return out
	case []any:
		out := make([]any, len(x))
		for i, v := range x {
			out[i] = normalizeJSON(v)
		}
		return out
	}
	return v
}

func TestEnvelopeInterop_CanonicalJSON(t *testing.T) {
	f := loadFixture(t)
	for i, v := range f.CanonicalJSONVectors {
		got, err := CanonicalJSON(v.Input)
		if err != nil {
			t.Errorf("vector %d: error %v", i, err)
			continue
		}
		if got != v.Expected {
			t.Errorf("vector %d:\n  got:  %s\n want:  %s", i, got, v.Expected)
		}
	}
}

func TestEnvelopeInterop_VerifyValid(t *testing.T) {
	f := loadFixture(t)
	r := VerifyEnvelope(VerifyEnvelopeOpts{
		Envelope: f.ValidEnvelope,
		NowMs:    Int64Ptr(f.VerifyNowMs),
	})
	if !r.OK {
		t.Fatalf("expected ok=true for valid_envelope; reason=%s", r.Reason)
	}
}

func TestEnvelopeInterop_RejectionVectors(t *testing.T) {
	f := loadFixture(t)
	for _, rv := range f.RejectionVectors {
		// The fixture's "expired" entry uses its own past expiresAt; verify
		// against verify_now_ms.
		r := VerifyEnvelope(VerifyEnvelopeOpts{
			Envelope: rv.Envelope,
			NowMs:    Int64Ptr(f.VerifyNowMs),
		})
		if r.OK {
			t.Errorf("rejection %q: expected ok=false", rv.Reason)
			continue
		}
		if string(r.Reason) != rv.Reason {
			t.Errorf("rejection %q: got reason=%s want=%s", rv.Reason, r.Reason, rv.Reason)
		}
	}
}

// TestEnvelopeInterop_CanonicalJSONRejectionVectors verifies that
// CanonicalJSON rejects inputs which RFC 8785 forbids. Per
// audits/canonical-json-rfc8785-parity.md §3 rec 6 (D6), the lone-surrogate
// case is the gating example. Each input is reconstructed from a UTF-16
// code-unit array so JSON-parser divergence (Go's encoding/json replaces lone
// surrogates with U+FFFD, Ruby errors at parse-time, etc.) does not mask the
// canonical_json behaviour we are gating.
func TestEnvelopeInterop_CanonicalJSONRejectionVectors(t *testing.T) {
	path := mustFixturePath(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var top map[string]any
	dec := json.NewDecoder(stringReader(string(raw)))
	dec.UseNumber()
	if err := dec.Decode(&top); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	rvs, _ := top["canonical_json_rejection_vectors"].([]any)
	if len(rvs) == 0 {
		t.Fatal("canonical_json_rejection_vectors missing or empty")
	}
	for _, raw := range rvs {
		v := raw.(map[string]any)
		id, _ := v["_vector_id"].(string)
		key, _ := v["input_object_key"].(string)
		units, _ := v["input_value_utf16_units"].([]any)
		// Build a Go string from UTF-16 units. Go strings are byte sequences;
		// utf16.Decode returns runes but a lone surrogate becomes
		// utf8.RuneError. We instead emit the surrogate as its WTF-8 / CESU-8
		// byte pattern so the canonical_json escaper sees the lone surrogate
		// rather than a replacement char.
		var bad []byte
		for _, u := range units {
			n, _ := u.(json.Number)
			cp, _ := n.Int64()
			// Encode lone surrogate as 3-byte UTF-8 of the surrogate value
			// itself (illegal but unambiguous; Go's range loop will yield
			// utf8.RuneError 0xFFFD on this).
			bad = append(bad, byte(0xe0|(cp>>12)), byte(0x80|((cp>>6)&0x3f)), byte(0x80|(cp&0x3f)))
		}
		input := map[string]any{key: string(bad)}
		got, err := CanonicalJSON(input)
		if err == nil {
			t.Errorf("vector %s: CanonicalJSON did NOT reject lone surrogate; got %s", id, got)
			continue
		}
		// R-262: assert WHY it was rejected. This used to check only that err
		// was non-nil, which passes for any reason at all — proven by
		// neutering CanonicalJSON to fail unconditionally, after which the
		// test stayed green.
		if !strings.Contains(err.Error(), "lone surrogate") {
			t.Errorf("vector %s: rejected for the wrong reason: %v", id, err)
		}

		// CONTROL: the same map, the same key, the same code path — the only
		// change is that U+D800 is now the HIGH half of a valid pair
		// (U+1F600). It must serialise, and byte-identically to every other
		// tier. Without this the test passes for a guard that rejects
		// everything.
		good, err := CanonicalJSON(map[string]any{key: "\U0001F600"})
		if err != nil {
			t.Errorf("vector %s: control (paired surrogate) was rejected: %v", id, err)
		} else if want := "{\"" + key + "\":\"\U0001F600\"}"; good != want {
			t.Errorf("vector %s: control got %s want %s", id, good, want)
		}
	}
}

func mustFixturePath(t *testing.T) string {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	return filepath.Join(filepath.Dir(thisFile), "..", "..", "conformance", "sdk-envelope", "fixtures.json")
}

// TestEnvelopeInterop_SigningVectors is the GAP-064 cross-tier signing
// reproduction: signing the SAME payload with the SAME key (priv=1) via RFC
// 6979 deterministic ECDSA (plain-SHA-256 nonce, low-S) MUST yield the
// byte-identical DER signature the TS reference committed. The testSigner's
// SignHash signs the 32-byte digest directly (go-sdk PrivateKey.Sign) and
// serializes low-S DER.
func TestEnvelopeInterop_SigningVectors(t *testing.T) {
	path := mustFixturePath(t)
	raw, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var top map[string]any
	dec := json.NewDecoder(stringReader(string(raw)))
	dec.UseNumber()
	if err := dec.Decode(&top); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	svs, _ := top["signing_vectors"].([]any)
	if len(svs) == 0 {
		t.Fatal("signing_vectors missing or empty")
	}
	alice := newAliceSigner(t)
	for _, e := range svs {
		v := e.(map[string]any)
		id, _ := v["_vector_id"].(string)
		expectedPayload := v["expected_payload"].(string)
		expectedSig := v["expected_sig"].(string)

		// Drift guard: re-derive the canonical payload from data + lifetime
		// fields and confirm it matches the committed expected_payload.
		data := normalizeJSON(v["data"]).(map[string]any)
		merged := make(map[string]any, len(data)+2)
		for k, val := range data {
			merged[k] = val
		}
		merged["nonce"] = normalizeJSON(v["nonce"])
		merged["expiresAt"] = normalizeJSON(v["expiresAt"])
		payload, err := CanonicalJSON(merged)
		if err != nil {
			t.Errorf("vector %s: CanonicalJSON error: %v", id, err)
			continue
		}
		if payload != expectedPayload {
			t.Errorf("vector %s: payload\n  got:  %s\n want:  %s", id, payload, expectedPayload)
			continue
		}

		// Sign sha256(expected_payload) with priv=1 deterministic ECDSA -> DER.
		d := sha256.Sum256([]byte(expectedPayload))
		der, err := alice.SignHash(d[:])
		if err != nil {
			t.Errorf("vector %s: sign: %v", id, err)
			continue
		}
		got := hex.EncodeToString(der)
		if got != expectedSig {
			t.Errorf("vector %s: signature divergence\n  got:  %s\n want:  %s", id, got, expectedSig)
		}
	}
}

// TestEnvelopeInterop_DepthVectors — R-260. VerifyEnvelope must bound payload
// nesting ITSELF rather than inherit whatever cap encoding/json happens to
// impose, because that cap differs per tier (ruby 100, rust 127, ts/go/python/
// zig none, java a StackOverflowError whose threshold is the JVM's -Xss flag).
// All seven tiers enforce MaxEnvelopePayloadDepth on the payload TEXT, so the
// same bytes get the same VerifyEnvelopeReason everywhere.
func TestEnvelopeInterop_DepthVectors(t *testing.T) {
	f := loadFixture(t)
	if len(f.DepthVectors) == 0 {
		t.Fatal("depth_vectors missing or empty")
	}
	for _, dv := range f.DepthVectors {
		r := VerifyEnvelope(VerifyEnvelopeOpts{Envelope: dv.Envelope, NowMs: Int64Ptr(f.VerifyNowMs)})
		if dv.ExpectOK {
			if !r.OK {
				t.Errorf("%s: expected ok=true, got reason=%s", dv.VectorID, r.Reason)
			}
			continue
		}
		if r.OK {
			t.Errorf("%s: expected ok=false", dv.VectorID)
			continue
		}
		if string(r.Reason) != dv.Reason {
			t.Errorf("%s: got reason=%s want=%s", dv.VectorID, r.Reason, dv.Reason)
		}
	}
}

// The bound is part of the wire contract, so the fixture pins it and every
// tier asserts its own constant against the fixture's number.
func TestEnvelopeInterop_PayloadDepthLimitMatchesFixture(t *testing.T) {
	f := loadFixture(t)
	if f.PayloadDepthLimit != MaxEnvelopePayloadDepth {
		t.Fatalf("fixture payload_depth_limit=%d, MaxEnvelopePayloadDepth=%d", f.PayloadDepthLimit, MaxEnvelopePayloadDepth)
	}
}

// TestEnvelopeInterop_ClockSkewVectors — R-261. An EXPLICIT clock skew of 0
// must mean 0, not "not supplied". Six tiers already distinguished the two;
// THIS tier conflated them (`ClockSkewMs int64 // defaults to 5_000 when
// zero`), so a caller asking for strict expiry silently got a five-second
// replay window — measured ok:true on the valid envelope 2000 ms past expiry
// where rust, python, ruby, zig and java all said expired. The same
// zero-value sentinel sat on NowMs. A nil in the vector means the caller
// supplies nothing and the tier default applies; cs2 and cs3 are the controls
// that redden if a fix made explicit zero strict by dropping the default.
func TestEnvelopeInterop_ClockSkewVectors(t *testing.T) {
	f := loadFixture(t)
	if len(f.ClockSkewVectors) == 0 {
		t.Fatal("clock_skew_vectors missing or empty")
	}
	for _, cv := range f.ClockSkewVectors {
		r := VerifyEnvelope(VerifyEnvelopeOpts{
			Envelope:    f.ValidEnvelope,
			ClockSkewMs: cv.ClockSkewMs,
			NowMs:       cv.NowMs,
		})
		if cv.ExpectOK {
			if !r.OK {
				t.Errorf("%s: expected ok=true, got reason=%s", cv.VectorID, r.Reason)
			}
			continue
		}
		if r.OK {
			t.Errorf("%s: expected ok=false", cv.VectorID)
			continue
		}
		if string(r.Reason) != cv.Reason {
			t.Errorf("%s: got reason=%s want=%s", cv.VectorID, r.Reason, cv.Reason)
		}
	}
}
