package runar

// Cross-tier interop test for the signed-envelope wire protocol. Reads the
// shared fixture at `conformance/sdk-envelope/fixtures.json` (generated by
// the TS reference impl) and asserts that:
//
//   1. CanonicalJSON produces byte-identical output for every documented input.
//   2. VerifyEnvelope returns OK=true for the valid envelope at verify_now_ms.
//   3. VerifyEnvelope returns the listed reason for every tampered envelope.
//
// Any failure here is a cross-tier protocol divergence. See CLAUDE.md §"Seven
// SDKs Must Stay in Sync" for the rationale.

import (
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

type fixtureCanonicalVector struct {
	Input    any    `json:"input"`
	Expected string `json:"expected"`
}

type fixtureRejection struct {
	Reason   string         `json:"reason"`
	Envelope SignedEnvelope `json:"envelope"`
}

type fixture struct {
	FixtureVersion       int                      `json:"fixture_version"`
	AlicePubHex          string                   `json:"alice_pub_hex"`
	Nonce                int64                    `json:"nonce"`
	ExpiresAt            int64                    `json:"expires_at"`
	VerifyNowMs          int64                    `json:"verify_now_ms"`
	CanonicalJSONVectors []fixtureCanonicalVector `json:"canonical_json_vectors"`
	ValidEnvelope        SignedEnvelope           `json:"valid_envelope"`
	RejectionVectors     []fixtureRejection       `json:"rejection_vectors"`
}

func loadFixture(t *testing.T) fixture {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(thisFile), "..", "..", "conformance", "sdk-envelope", "fixtures.json")
	bytes, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	dec := json.NewDecoder(stringReader(string(bytes)))
	dec.UseNumber()
	var raw map[string]any
	if err := dec.Decode(&raw); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}

	// Round-trip into our typed shape via re-encoding so json.Number-typed
	// nonce/expiresAt fields land in the right places.
	var f fixture
	if err := json.Unmarshal(bytes, &f); err != nil {
		t.Fatalf("unmarshal fixture: %v", err)
	}
	// Re-decode CanonicalJSONVectors with UseNumber semantics so the
	// inputs preserve int-vs-float intent identically to the JS source.
	cv := raw["canonical_json_vectors"].([]any)
	f.CanonicalJSONVectors = make([]fixtureCanonicalVector, len(cv))
	for i, e := range cv {
		obj := e.(map[string]any)
		f.CanonicalJSONVectors[i] = fixtureCanonicalVector{
			Input:    normalizeJSON(obj["input"]),
			Expected: obj["expected"].(string),
		}
	}
	return f
}

// normalizeJSON converts json.Number leaves into int64 (when exact) or float64
// so they match what the TS source value would have been. CanonicalJSON
// handles both, but the inputs need stable types per leaf.
func normalizeJSON(v any) any {
	switch x := v.(type) {
	case json.Number:
		if i, err := x.Int64(); err == nil {
			return i
		}
		f, _ := x.Float64()
		return f
	case map[string]any:
		out := make(map[string]any, len(x))
		for k, v := range x {
			out[k] = normalizeJSON(v)
		}
		return out
	case []any:
		out := make([]any, len(x))
		for i, v := range x {
			out[i] = normalizeJSON(v)
		}
		return out
	}
	return v
}

func TestEnvelopeInterop_CanonicalJSON(t *testing.T) {
	f := loadFixture(t)
	for i, v := range f.CanonicalJSONVectors {
		got, err := CanonicalJSON(v.Input)
		if err != nil {
			t.Errorf("vector %d: error %v", i, err)
			continue
		}
		if got != v.Expected {
			t.Errorf("vector %d:\n  got:  %s\n want:  %s", i, got, v.Expected)
		}
	}
}

func TestEnvelopeInterop_VerifyValid(t *testing.T) {
	f := loadFixture(t)
	r := VerifyEnvelope(VerifyEnvelopeOpts{
		Envelope: f.ValidEnvelope,
		NowMs:    f.VerifyNowMs,
	})
	if !r.OK {
		t.Fatalf("expected ok=true for valid_envelope; reason=%s", r.Reason)
	}
}

func TestEnvelopeInterop_RejectionVectors(t *testing.T) {
	f := loadFixture(t)
	for _, rv := range f.RejectionVectors {
		// The fixture's "expired" entry uses its own past expiresAt; verify
		// against verify_now_ms.
		r := VerifyEnvelope(VerifyEnvelopeOpts{
			Envelope: rv.Envelope,
			NowMs:    f.VerifyNowMs,
		})
		if r.OK {
			t.Errorf("rejection %q: expected ok=false", rv.Reason)
			continue
		}
		if string(r.Reason) != rv.Reason {
			t.Errorf("rejection %q: got reason=%s want=%s", rv.Reason, r.Reason, rv.Reason)
		}
	}
}
