package runar

// Cross-tier BIP-143 sighash interop test (GAP-003). Reads the shared fixture
// at `conformance/sdk-bip143/fixtures.json` (generated by the TS reference impl
// via @bsv/sdk TransactionSignature.format) and asserts, for every scenario:
//
//  1. This tier INDEPENDENTLY recomputes the full BIP-143 preimage from
//     (unsignedTxHex, inputIndex, prevScriptHex, prevValueSats) and it is
//     byte-identical to the fixture's preimageHex. This is the core cross-tier
//     correctness check and needs NO node.
//  2. sha256d(preimage) == the fixture's digestHex (the value ECDSA signs).
//  3. The fixture's TS-produced sigHex verifies against pubkeyHex over this
//     tier's own computed digest.
//
// Any failure here is a cross-tier BIP-143 protocol divergence — a real
// consensus bug, not a test bug. See CLAUDE.md §"Seven SDKs Must Stay in Sync"
// and conformance/sdk-bip143/.

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"os"
	"path/filepath"
	"runtime"
	"testing"
)

type bip143Scenario struct {
	Scenario      string `json:"scenario"`
	Description   string `json:"description"`
	UnsignedTxHex string `json:"unsignedTxHex"`
	InputIndex    int    `json:"inputIndex"`
	PrevScriptHex string `json:"prevScriptHex"`
	PrevValueSats int64  `json:"prevValueSats"`
	SighashFlags  int    `json:"sighashFlags"`
	PreimageHex   string `json:"preimageHex"`
	DigestHex     string `json:"digestHex"`
	SigHex        string `json:"sigHex"`
	PubkeyHex     string `json:"pubkeyHex"`
}

type bip143Fixture struct {
	FixtureVersion int              `json:"fixture_version"`
	SignerPubHex   string           `json:"signer_pub_hex"`
	Scenarios      []bip143Scenario `json:"scenarios"`
}

func loadBip143Fixture(t *testing.T) bip143Fixture {
	t.Helper()
	_, thisFile, _, _ := runtime.Caller(0)
	path := filepath.Join(filepath.Dir(thisFile), "..", "..", "conformance", "sdk-bip143", "fixtures.json")
	bytes, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var f bip143Fixture
	if err := json.Unmarshal(bytes, &f); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	if len(f.Scenarios) == 0 {
		t.Fatal("fixture has no scenarios")
	}
	return f
}

func sha256dHex(b []byte) string {
	first := sha256.Sum256(b)
	second := sha256.Sum256(first[:])
	return hex.EncodeToString(second[:])
}

func TestBip143Interop_PreimageAndSignature(t *testing.T) {
	f := loadBip143Fixture(t)
	for _, s := range f.Scenarios {
		s := s
		t.Run(s.Scenario, func(t *testing.T) {
			// 1. Independently recompute the BIP-143 preimage under the
			//    scenario's OWN sighash flags.
			//
			//    R-206: this used to reject anything but 0x41. Every scenario in
			//    the fixture was ALL|FORKID, so the per-mode zeroing rules —
			//    hashPrevouts under ANYONECANPAY, hashSequence unless pure ALL,
			//    hashOutputs under NONE and the single-output rule under SINGLE
			//    — were implemented seven times and compared zero times.
			_, preimage, err := ComputeOpPushTxWithSigHash(
				s.UnsignedTxHex, s.InputIndex, s.PrevScriptHex, s.PrevValueSats, -1, s.SighashFlags)
			if err != nil {
				t.Fatalf("ComputeOpPushTx: %v", err)
			}
			gotPreimage := hex.EncodeToString(preimage)
			if gotPreimage != s.PreimageHex {
				t.Fatalf("BIP-143 PREIMAGE DIVERGENCE from TS reference:\n  want %s\n  got  %s", s.PreimageHex, gotPreimage)
			}

			// 2. sha256d(preimage) must equal the published digest.
			gotDigest := sha256dHex(preimage)
			if gotDigest != s.DigestHex {
				t.Fatalf("sighash digest divergence:\n  want %s\n  got  %s", s.DigestHex, gotDigest)
			}

			// 3. The TS-produced signature must verify over this tier's digest.
			digestBytes, _ := hex.DecodeString(gotDigest)
			sigBytes, err := hex.DecodeString(s.SigHex)
			if err != nil {
				t.Fatalf("decode sigHex: %v", err)
			}
			// Strip the trailing sighash byte (DER sig only for verify).
			derSig := sigBytes[:len(sigBytes)-1]
			pubkey, err := hex.DecodeString(s.PubkeyHex)
			if err != nil {
				t.Fatalf("decode pubkeyHex: %v", err)
			}
			if !ecdsaVerify(derSig, pubkey, digestBytes) {
				t.Fatalf("TS reference signature does not verify under this tier's digest (pubkey %s)", s.PubkeyHex)
			}
		})
	}
}
