/**
 * Pass 7: SX Emit — converts ANF IR to BitcoinSX (.sx) text.
 *
 * This is a parallel backend to passes 05+06 (stack-lower + emit-hex).
 * It operates on the same ANF IR input but preserves high-level structure:
 *
 *   - Private methods → SX `#macros`
 *   - Loops → SX `repeat Nn ... end`
 *   - If/else → SX `if ... else ... endIf`
 *   - Constructor params → SX `.variables`
 *   - Opcodes → SX camelCase names
 */

import type { ANFProgram, ANFMethod, ANFBinding, ANFProperty } from '../ir/index.js';
import type { SXEmitResult, SXSection } from '../ir/sx-ir.js';
import { SXStackScheduler, analyzeMethodStackEffect } from './07-sx-stack.js';

// ---------------------------------------------------------------------------
// Public API
// ---------------------------------------------------------------------------

/**
 * Emit an ANFProgram as BitcoinSX text.
 */
export function emitSX(program: ANFProgram): SXEmitResult {
  const sections: SXSection[] = [];
  const lines: string[] = [];

  // -----------------------------------------------------------------------
  // Header
  // -----------------------------------------------------------------------

  const headerLines: string[] = [];
  headerLines.push(`// ${program.contractName}.sx — generated by Runar compiler`);

  // Constructor variables
  const ctorProps = program.properties.filter(p => p.initialValue === undefined);
  if (ctorProps.length > 0) {
    headerLines.push('//');
    headerLines.push('// Constructor:');
    for (const prop of ctorProps) {
      headerLines.push(`//   .${prop.name}: ${prop.type}`);
    }
  }

  const headerSx = headerLines.join('\n');
  sections.push({ kind: 'comment', name: 'header', sx: headerSx });
  lines.push(headerSx);
  lines.push('');

  // -----------------------------------------------------------------------
  // Collect private methods
  // -----------------------------------------------------------------------

  const privateMethods = new Map<string, ANFMethod>();
  const publicMethods: ANFMethod[] = [];

  for (const method of program.methods) {
    if (method.name === 'constructor') continue;
    if (method.isPublic) {
      publicMethods.push(method);
    } else {
      privateMethods.set(method.name, method);
    }
  }

  // -----------------------------------------------------------------------
  // Emit private methods as #macros
  // -----------------------------------------------------------------------

  for (const [name, method] of privateMethods) {
    const macroLines: string[] = [];
    macroLines.push(`#${name}`);

    // Document params
    if (method.params.length > 0) {
      const paramList = method.params.map(p => `${p.name}: ${p.type}`).join(', ');
      macroLines.push(`  // params: ${paramList}`);
    }

    // Lower the method body
    // Macro calling convention: args are on stack in parameter order,
    // param[0] at bottom, param[N-1] at top
    const paramNames = method.params.map(p => p.name);
    const scheduler = new SXStackScheduler(
      paramNames,
      program.properties,
      privateMethods,
      '  ',
    );

    const effect = analyzeMethodStackEffect(method);
    const isTerminal = effect.produces === 0;
    scheduler.lowerBindings(method.body, !isTerminal);

    if (!isTerminal) {
      scheduler.cleanupExcessStack();
    }

    const bodyText = scheduler.getOutput();
    if (bodyText) macroLines.push(bodyText);
    macroLines.push('end');

    const macroSx = macroLines.join('\n');
    sections.push({ kind: 'macro', name, sx: macroSx });
    lines.push(macroSx);
    lines.push('');
  }

  // -----------------------------------------------------------------------
  // Emit public methods
  // -----------------------------------------------------------------------

  if (publicMethods.length === 0) {
    // No public methods — empty contract
    return { sx: lines.join('\n'), sections };
  }

  if (publicMethods.length === 1) {
    // Single public method — emit body directly
    const method = publicMethods[0]!;
    const bodySx = emitMethodBody(method, program.properties, privateMethods);
    sections.push({ kind: 'body', name: method.name, sx: bodySx });
    lines.push(`// Public method: ${method.name}(${formatParams(method)})`);
    lines.push(bodySx);
  } else {
    // Multiple public methods — emit dispatch
    const dispatchSx = emitDispatch(publicMethods, program.properties, privateMethods);
    sections.push({ kind: 'dispatch', name: 'dispatch', sx: dispatchSx });
    lines.push(dispatchSx);
  }

  return { sx: lines.join('\n'), sections };
}

// ---------------------------------------------------------------------------
// Helpers
// ---------------------------------------------------------------------------

function formatParams(method: ANFMethod): string {
  return method.params
    .filter(p => !p.name.startsWith('_')) // skip implicit params
    .map(p => `${p.name}: ${p.type}`)
    .join(', ');
}

/**
 * Build the parameter list for a public method's initial stack.
 * In Bitcoin Script, scriptSig args are pushed in order: first arg at bottom,
 * last arg at top. Implicit params (prefixed with _) are included because
 * they're part of the scriptSig.
 *
 * For stateful contracts, the hex backend injects implicit params:
 * - _opPushTxSig: ECDSA sig for OP_PUSH_TX verification
 * - _codePart: full code script (when method uses add_output/add_raw_output/computeStateOutput)
 * These must be on the stack for the delegated stateful intrinsics to work.
 */
function buildMethodParams(method: ANFMethod): string[] {
  const paramNames = method.params.map(p => p.name);

  if (methodUsesCheckPreimage(method.body)) {
    paramNames.unshift('_opPushTxSig');
    if (methodUsesCodePart(method.body)) {
      paramNames.unshift('_codePart');
    }
  }

  return paramNames;
}

function methodUsesCheckPreimage(bindings: ANFBinding[]): boolean {
  for (const b of bindings) {
    if (b.value.kind === 'check_preimage') return true;
  }
  return false;
}

function methodUsesCodePart(bindings: ANFBinding[]): boolean {
  for (const b of bindings) {
    if (b.value.kind === 'add_output' || b.value.kind === 'add_raw_output') return true;
    if (b.value.kind === 'call' && (b.value.func === 'computeStateOutput' || b.value.func === 'computeStateOutputHash')) return true;
    if (b.value.kind === 'if') {
      if (methodUsesCodePart(b.value.then) || methodUsesCodePart(b.value.else)) return true;
    }
    if (b.value.kind === 'loop' && methodUsesCodePart(b.value.body)) return true;
  }
  return false;
}

/**
 * Emit a single method body as SX text.
 */
function emitMethodBody(
  method: ANFMethod,
  properties: ANFProperty[],
  privateMethods: Map<string, ANFMethod>,
): string {
  const paramNames = buildMethodParams(method);
  const scheduler = new SXStackScheduler(
    paramNames,
    properties,
    privateMethods,
  );

  scheduler.lowerBindings(method.body, true);
  scheduler.cleanupExcessStack();

  return scheduler.getOutput();
}

/**
 * Emit a method dispatch structure for multiple public methods.
 *
 * The spending transaction pushes the method index as the topmost
 * scriptSig element. Pattern:
 *
 *   dup 0n numEqual if drop <method0> else
 *   dup 1n numEqual if drop <method1> else
 *   Nn numEqualVerify <methodN>
 *   endIf endIf ...
 */
function emitDispatch(
  methods: ANFMethod[],
  properties: ANFProperty[],
  privateMethods: Map<string, ANFMethod>,
): string {
  const lines: string[] = [];
  lines.push('// Method dispatch');

  for (let i = 0; i < methods.length; i++) {
    const method = methods[i]!;
    const isLast = i === methods.length - 1;

    lines.push('');
    lines.push(`// [${i}] ${method.name}(${formatParams(method)})`);

    if (!isLast) {
      lines.push('dup');
      lines.push(`${i}n numEqual`);
      lines.push('if');
      lines.push('  drop');

      // Emit method body indented
      const paramNames = buildMethodParams(method);
      const scheduler = new SXStackScheduler(
        paramNames,
        properties,
        privateMethods,
        '  ',
      );
      scheduler.lowerBindings(method.body, true);
      scheduler.cleanupExcessStack();
      const bodyText = scheduler.getOutput();
      if (bodyText) lines.push(bodyText);

      lines.push('else');
    } else {
      // Last method — verify and emit directly
      lines.push(`${i}n numEqualVerify`);

      const paramNames = buildMethodParams(method);
      const scheduler = new SXStackScheduler(
        paramNames,
        properties,
        privateMethods,
      );
      scheduler.lowerBindings(method.body, true);
      scheduler.cleanupExcessStack();
      const bodyText = scheduler.getOutput();
      if (bodyText) lines.push(bodyText);
    }
  }

  // Close all the nested if/else blocks
  for (let i = 0; i < methods.length - 1; i++) {
    lines.push('endIf');
  }

  return lines.join('\n');
}
