package runar.lang.sdk.codegen;

import java.io.ByteArrayOutputStream;
import java.io.IOException;
import java.lang.reflect.Constructor;
import java.lang.reflect.Method;
import java.math.BigInteger;
import java.net.URI;
import java.nio.charset.StandardCharsets;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.stream.Collectors;

import javax.tools.Diagnostic;
import javax.tools.DiagnosticCollector;
import javax.tools.ForwardingJavaFileManager;
import javax.tools.JavaCompiler;
import javax.tools.JavaFileManager;
import javax.tools.JavaFileObject;
import javax.tools.SimpleJavaFileObject;
import javax.tools.StandardJavaFileManager;
import javax.tools.ToolProvider;

import org.junit.jupiter.api.Test;

import runar.lang.sdk.RunarArtifact;
import runar.lang.sdk.RunarArtifact.ABI;
import runar.lang.sdk.RunarArtifact.ABIConstructor;
import runar.lang.sdk.RunarArtifact.ABIMethod;
import runar.lang.sdk.RunarArtifact.ABIParam;
import runar.lang.sdk.RunarArtifact.StateField;
import runar.lang.types.Addr;
import runar.lang.types.PubKey;
import runar.lang.types.Sig;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.junit.jupiter.api.Assertions.fail;

class TypedContractGeneratorTest {

    // ---------------------------------------------------------------------
    // Golden string — exact (modulo whitespace) match of P2PKH output
    // ---------------------------------------------------------------------

    @Test
    void generatesExpectedP2pkhSource() {
        RunarArtifact artifact = buildP2PKHArtifact();
        String src = TypedContractGenerator.generate(artifact, "runar.generated.p2pkh");

        String expected = """
            // Generated by: runar codegen
            // Source: P2PKH
            // Do not edit manually.

            package runar.generated.p2pkh;

            import java.math.BigInteger;
            import java.util.ArrayList;
            import java.util.List;
            import runar.lang.sdk.Provider;
            import runar.lang.sdk.RunarArtifact;
            import runar.lang.sdk.RunarContract;
            import runar.lang.sdk.Signer;
            import runar.lang.types.Addr;
            import runar.lang.types.PubKey;

            public final class P2PKHWrapper {
                private final RunarContract inner;
                private final Provider provider;
                private final Signer signer;

                public P2PKHWrapper(RunarArtifact artifact, Addr pubKeyHash, Provider provider, Signer signer) {
                    List<Object> args = new ArrayList<>();
                    args.add(pubKeyHash.toHex());
                    this.inner = new RunarContract(artifact, args);
                    this.provider = provider;
                    this.signer = signer;
                }

                /** Returns the underlying {@link RunarContract}. */
                public RunarContract contract() {
                    return inner;
                }

                /** Deploys the contract on-chain. Returns the broadcast txid. */
                public String deploy(BigInteger satoshis) {
                    return inner.deploy(provider, signer, satoshis.longValueExact()).txid();
                }

                /** Terminal method: unlock. */
                public void unlock(PubKey pubKey) {
                    List<Object> callArgs = new ArrayList<>();
                    callArgs.add(null); // Sig auto-computed by SDK
                    callArgs.add(pubKey.toHex());
                    inner.call("unlock", callArgs, null, provider, signer);
                }
            }
            """;

        assertEquals(normalize(expected), normalize(src),
            "generated P2PKH source did not match golden\n--- actual ---\n" + src);
    }

    // ---------------------------------------------------------------------
    // Compilation — in-memory javac on the generated source
    // ---------------------------------------------------------------------

    @Test
    void generatedP2pkhCompilesCleanly() throws Exception {
        RunarArtifact artifact = buildP2PKHArtifact();
        String src = TypedContractGenerator.generate(artifact, "runar.generated.p2pkh");
        Class<?> cls = compileInMemory("runar.generated.p2pkh.P2PKHWrapper", src);
        assertEquals("P2PKHWrapper", cls.getSimpleName());
    }

    @Test
    void generatedConstructorMatchesExpectedSignature() throws Exception {
        RunarArtifact artifact = buildP2PKHArtifact();
        String src = TypedContractGenerator.generate(artifact, "runar.generated.p2pkh");
        Class<?> cls = compileInMemory("runar.generated.p2pkh.P2PKHWrapper", src);

        Constructor<?>[] ctors = cls.getDeclaredConstructors();
        assertEquals(1, ctors.length, "expected exactly one constructor");
        Class<?>[] params = ctors[0].getParameterTypes();
        assertEquals(4, params.length, "constructor should take (artifact, pubKeyHash, provider, signer)");
        assertEquals(RunarArtifact.class, params[0]);
        assertEquals(Addr.class, params[1]);
        assertEquals(runar.lang.sdk.Provider.class, params[2]);
        assertEquals(runar.lang.sdk.Signer.class, params[3]);
    }

    @Test
    void generatedP2pkhHasVoidUnlockWithPubKeyOnly() throws Exception {
        RunarArtifact artifact = buildP2PKHArtifact();
        String src = TypedContractGenerator.generate(artifact, "runar.generated.p2pkh");
        Class<?> cls = compileInMemory("runar.generated.p2pkh.P2PKHWrapper", src);

        Method unlock = cls.getDeclaredMethod("unlock", PubKey.class);
        assertEquals(void.class, unlock.getReturnType(),
            "stateless (terminal) methods should return void");

        // Sig param must be elided from the signature (auto-computed by SDK).
        for (Method m : cls.getDeclaredMethods()) {
            if ("unlock".equals(m.getName())) {
                assertFalse(Arrays.asList(m.getParameterTypes()).contains(Sig.class),
                    "unlock() must not declare a Sig parameter");
            }
        }
    }

    // ---------------------------------------------------------------------
    // Stateful (Counter) — typed method + state accessor
    // ---------------------------------------------------------------------

    @Test
    void generatesTypedStatefulCounterWrapper() throws Exception {
        RunarArtifact artifact = buildCounterArtifact();
        String src = TypedContractGenerator.generate(artifact, "runar.generated.counter");
        Class<?> cls = compileInMemory("runar.generated.counter.CounterWrapper", src);

        // Typed increment(BigInteger amount) → String (stateful, non-terminal)
        Method increment = cls.getDeclaredMethod("increment", BigInteger.class);
        assertEquals(String.class, increment.getReturnType(),
            "stateful non-terminal methods must return the txid String");

        // Typed state accessor count() → BigInteger
        Method count = cls.getDeclaredMethod("count");
        assertEquals(BigInteger.class, count.getReturnType(),
            "state accessor for bigint field must return BigInteger");

        // Stateful reset method (terminal: no _changePKH) → void
        Method reset = cls.getDeclaredMethod("reset");
        assertEquals(void.class, reset.getReturnType(),
            "terminal stateful methods must return void");

        // Source-level sanity: cast expression for state accessor and ABI call.
        assertTrue(src.contains("(BigInteger) inner.state(\"count\")"),
            "state accessor must cast Object returned by inner.state()");
        assertTrue(src.contains("inner.call(\"increment\""),
            "generated wrapper must delegate to inner.call()");
    }

    @Test
    void generatedCounterWrapperCompilesCleanly() throws Exception {
        RunarArtifact artifact = buildCounterArtifact();
        String src = TypedContractGenerator.generate(artifact, "runar.generated.counter");
        Class<?> cls = compileInMemory("runar.generated.counter.CounterWrapper", src);
        assertNotNull(cls);
    }

    // ---------------------------------------------------------------------
    // Fixtures
    // ---------------------------------------------------------------------

    private static RunarArtifact buildP2PKHArtifact() {
        ABIConstructor ctor = new ABIConstructor(List.of(
            new ABIParam("pubKeyHash", "Addr", null)
        ));
        ABIMethod unlock = new ABIMethod(
            "unlock",
            List.of(
                new ABIParam("sig", "Sig", null),
                new ABIParam("pubKey", "PubKey", null)
            ),
            true, null
        );
        return new RunarArtifact(
            "runar-v0.1.0", "0.1.0", "P2PKH",
            new ABI(ctor, List.of(unlock)),
            "a9007c7c9c69007c7cac69",
            "OP_HASH160 OP_0 OP_SWAP OP_SWAP OP_NUMEQUAL OP_VERIFY OP_0 OP_SWAP OP_SWAP OP_CHECKSIG OP_VERIFY",
            "2026-04-24T00:00:00Z",
            null, null, null, null, null
        );
    }

    /**
     * Stateful Counter with a {@code count} bigint state field, an
     * {@code increment(amount)} non-terminal method, and a terminal
     * {@code reset()} method.
     */
    private static RunarArtifact buildCounterArtifact() {
        ABIConstructor ctor = new ABIConstructor(List.of(
            new ABIParam("count", "bigint", null)
        ));
        // Non-terminal: has _changePKH
        ABIMethod increment = new ABIMethod(
            "increment",
            List.of(
                new ABIParam("amount", "bigint", null),
                new ABIParam("txPreimage", "SigHashPreimage", null),
                new ABIParam("_changePKH", "ByteString", null),
                new ABIParam("_changeAmount", "bigint", null)
            ),
            true,
            false
        );
        // Terminal stateful (no continuation): no _changePKH
        ABIMethod reset = new ABIMethod(
            "reset",
            List.of(
                new ABIParam("txPreimage", "SigHashPreimage", null)
            ),
            true,
            true
        );
        return new RunarArtifact(
            "runar-v0.1.0", "0.1.0", "Counter",
            new ABI(ctor, List.of(increment, reset)),
            "76009c63",  // placeholder script, irrelevant for codegen
            "OP_DUP OP_0 OP_NUMEQUAL OP_IF",
            "2026-04-24T00:00:00Z",
            List.of(new StateField("count", "bigint", 0, null, null)),
            null, null, null, null
        );
    }

    // ---------------------------------------------------------------------
    // In-memory Java compilation harness
    // ---------------------------------------------------------------------

    /** Compiles {@code source} for {@code fqcn}, loads and returns the class. */
    private static Class<?> compileInMemory(String fqcn, String source) throws Exception {
        JavaCompiler compiler = ToolProvider.getSystemJavaCompiler();
        assertNotNull(compiler,
            "javax.tools.JavaCompiler not available — run tests on a JDK (not a JRE)");

        DiagnosticCollector<JavaFileObject> diagnostics = new DiagnosticCollector<>();
        StandardJavaFileManager stdManager = compiler.getStandardFileManager(diagnostics, null, StandardCharsets.UTF_8);

        // Forward the host JVM's runtime classpath so the generated source
        // can resolve RunarContract, Addr, PubKey, etc. JUnit's console
        // launcher is typically invoked via {@code java -jar}, so
        // {@code java.class.path} only names that jar. Resolve each
        // reachable type to its code source to rebuild the real classpath.
        List<java.io.File> cpEntries = new ArrayList<>();
        for (Class<?> anchor : List.of(
            RunarArtifact.class,
            runar.lang.sdk.RunarContract.class,
            runar.lang.sdk.Provider.class,
            runar.lang.sdk.Signer.class,
            runar.lang.types.ByteString.class,
            runar.lang.types.Addr.class,
            runar.lang.types.PubKey.class,
            runar.lang.types.Sig.class,
            TypedContractGenerator.class
        )) {
            java.security.CodeSource cs = anchor.getProtectionDomain().getCodeSource();
            if (cs == null || cs.getLocation() == null) continue;
            try {
                java.io.File f = new java.io.File(cs.getLocation().toURI());
                if (!cpEntries.contains(f)) cpEntries.add(f);
            } catch (Exception ignore) {
                // fall through — unreachable in test context
            }
        }
        String runtimeCp = System.getProperty("java.class.path");
        if (runtimeCp != null) {
            for (String entry : runtimeCp.split(java.io.File.pathSeparator)) {
                if (entry.isEmpty()) continue;
                java.io.File f = new java.io.File(entry);
                if (!cpEntries.contains(f)) cpEntries.add(f);
            }
        }
        stdManager.setLocation(javax.tools.StandardLocation.CLASS_PATH, cpEntries);

        InMemoryFileManager fileManager = new InMemoryFileManager(stdManager);

        JavaFileObject file = new InMemorySourceFile(fqcn, source);
        // Use -source/-target rather than --release: the latter resets the
        // boot classpath in a way that drops our StandardLocation.CLASS_PATH
        // override, so the generated source can't resolve runar.lang.*.
        List<String> options = Arrays.asList("-source", "17", "-target", "17");
        JavaCompiler.CompilationTask task = compiler.getTask(
            null, fileManager, diagnostics, options, null, List.of(file)
        );

        boolean ok = task.call();
        if (!ok) {
            String errors = diagnostics.getDiagnostics().stream()
                .filter(d -> d.getKind() == Diagnostic.Kind.ERROR)
                .map(d -> d.getLineNumber() + ": " + d.getMessage(null))
                .collect(Collectors.joining("\n"));
            fail("generated source failed to compile:\n" + errors + "\n--- source ---\n" + source);
        }

        InMemoryClassLoader loader = new InMemoryClassLoader(
            TypedContractGeneratorTest.class.getClassLoader(), fileManager.classes
        );
        return loader.loadClass(fqcn);
    }

    // -- File manager storing .class bytes in memory --------------------

    private static final class InMemorySourceFile extends SimpleJavaFileObject {
        private final String source;

        InMemorySourceFile(String fqcn, String source) {
            super(URI.create("string:///" + fqcn.replace('.', '/') + Kind.SOURCE.extension),
                Kind.SOURCE);
            this.source = source;
        }

        @Override
        public CharSequence getCharContent(boolean ignoreEncodingErrors) {
            return source;
        }
    }

    private static final class InMemoryClassFile extends SimpleJavaFileObject {
        final ByteArrayOutputStream buf = new ByteArrayOutputStream();

        InMemoryClassFile(String fqcn) {
            super(URI.create("bytes:///" + fqcn.replace('.', '/') + Kind.CLASS.extension),
                Kind.CLASS);
        }

        @Override
        public java.io.OutputStream openOutputStream() {
            return buf;
        }
    }

    private static final class InMemoryFileManager
        extends ForwardingJavaFileManager<StandardJavaFileManager> {

        final Map<String, InMemoryClassFile> classes = new HashMap<>();

        InMemoryFileManager(StandardJavaFileManager delegate) {
            super(delegate);
        }

        @Override
        public JavaFileObject getJavaFileForOutput(Location location, String className,
                                                   JavaFileObject.Kind kind, javax.tools.FileObject sibling)
            throws IOException {
            if (kind == JavaFileObject.Kind.CLASS) {
                InMemoryClassFile f = new InMemoryClassFile(className);
                classes.put(className, f);
                return f;
            }
            return super.getJavaFileForOutput(location, className, kind, sibling);
        }
    }

    private static final class InMemoryClassLoader extends ClassLoader {
        private final Map<String, InMemoryClassFile> classes;

        InMemoryClassLoader(ClassLoader parent, Map<String, InMemoryClassFile> classes) {
            super(parent);
            this.classes = classes;
        }

        @Override
        protected Class<?> findClass(String name) throws ClassNotFoundException {
            InMemoryClassFile f = classes.get(name);
            if (f == null) throw new ClassNotFoundException(name);
            byte[] bytes = f.buf.toByteArray();
            return defineClass(name, bytes, 0, bytes.length);
        }
    }

    // ---------------------------------------------------------------------
    // Whitespace-insensitive comparison for golden assertion
    // ---------------------------------------------------------------------

    private static String normalize(String s) {
        // Collapse all whitespace runs to a single space and strip leading /
        // trailing whitespace per line — matches brief's "modulo whitespace".
        List<String> lines = new ArrayList<>();
        for (String raw : s.split("\n")) {
            String trimmed = raw.trim().replaceAll("\\s+", " ");
            if (!trimmed.isEmpty()) lines.add(trimmed);
        }
        return String.join("\n", lines);
    }

    // Keep linters from complaining about unused imports.
    @SuppressWarnings("unused")
    private static final Object KEEP_IMPORTS = Collections.unmodifiableList(new ArrayList<Object>());
}
