package contract

import (
	"testing"

	runar "github.com/icellan/runar/packages/runar-go"
)

// Helper: generate a point from a small scalar for use in tests.
// Uses EcMulGen which does real secp256k1 scalar multiplication.
func testPoint(scalar int64) runar.Point {
	return runar.EcMulGen(scalar)
}

// ---------------------------------------------------------------------------
// checkX (ecPointX)
// ---------------------------------------------------------------------------

func TestECDemo_CheckX(t *testing.T) {
	pt := testPoint(7)
	expectedX := runar.EcPointX(pt)
	c := &ECDemo{Pt: pt}
	c.CheckX(expectedX) // should not panic
}

func TestECDemo_CheckX_WrongValue(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong x-coordinate")
		}
	}()

	pt := testPoint(7)
	c := &ECDemo{Pt: pt}
	c.CheckX(999)
}

// ---------------------------------------------------------------------------
// checkY (ecPointY)
// ---------------------------------------------------------------------------

func TestECDemo_CheckY(t *testing.T) {
	pt := testPoint(7)
	expectedY := runar.EcPointY(pt)
	c := &ECDemo{Pt: pt}
	c.CheckY(expectedY)
}

func TestECDemo_CheckY_WrongValue(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong y-coordinate")
		}
	}()

	pt := testPoint(7)
	c := &ECDemo{Pt: pt}
	c.CheckY(999)
}

// ---------------------------------------------------------------------------
// checkMakePoint (ecMakePoint)
// ---------------------------------------------------------------------------

func TestECDemo_CheckMakePoint(t *testing.T) {
	// Use small values that fit cleanly in int64
	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	c.CheckMakePoint(10, 20, 10, 20)
}

func TestECDemo_CheckMakePoint_WrongExpected(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong make-point result")
		}
	}()

	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	c.CheckMakePoint(10, 20, 10, 99)
}

// ---------------------------------------------------------------------------
// checkOnCurve (ecOnCurve)
// ---------------------------------------------------------------------------

func TestECDemo_CheckOnCurve(t *testing.T) {
	// Points generated by EcMulGen are always on the curve
	pt := testPoint(42)
	c := &ECDemo{Pt: pt}
	c.CheckOnCurve()
}

// ---------------------------------------------------------------------------
// checkAdd (ecAdd)
// ---------------------------------------------------------------------------

func TestECDemo_CheckAdd(t *testing.T) {
	pt := testPoint(3)
	other := testPoint(5)
	sum := runar.EcAdd(pt, other)
	expectedX := runar.EcPointX(sum)
	expectedY := runar.EcPointY(sum)

	c := &ECDemo{Pt: pt}
	c.CheckAdd(other, expectedX, expectedY)
}

func TestECDemo_CheckAdd_WrongResult(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong add result")
		}
	}()

	pt := testPoint(3)
	other := testPoint(5)

	c := &ECDemo{Pt: pt}
	c.CheckAdd(other, 0, 0)
}

// ---------------------------------------------------------------------------
// checkMul (ecMul)
// ---------------------------------------------------------------------------

func TestECDemo_CheckMul(t *testing.T) {
	pt := testPoint(3)
	scalar := int64(7)
	product := runar.EcMul(pt, scalar)
	expectedX := runar.EcPointX(product)
	expectedY := runar.EcPointY(product)

	c := &ECDemo{Pt: pt}
	c.CheckMul(scalar, expectedX, expectedY)
}

func TestECDemo_CheckMul_WrongScalar(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong scalar result")
		}
	}()

	pt := testPoint(3)
	product := runar.EcMul(pt, 7)
	expectedX := runar.EcPointX(product)
	expectedY := runar.EcPointY(product)

	c := &ECDemo{Pt: pt}
	// Pass scalar=8 but expect result for scalar=7
	c.CheckMul(8, expectedX, expectedY)
}

// ---------------------------------------------------------------------------
// checkMulGen (ecMulGen)
// ---------------------------------------------------------------------------

func TestECDemo_CheckMulGen(t *testing.T) {
	pt := testPoint(1)
	scalar := int64(42)
	gen := runar.EcMulGen(scalar)
	expectedX := runar.EcPointX(gen)
	expectedY := runar.EcPointY(gen)

	c := &ECDemo{Pt: pt}
	c.CheckMulGen(scalar, expectedX, expectedY)
}

func TestECDemo_CheckMulGen_WrongExpected(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong mulgen result")
		}
	}()

	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	c.CheckMulGen(42, 0, 0)
}

// ---------------------------------------------------------------------------
// checkNegate (ecNegate)
// ---------------------------------------------------------------------------

func TestECDemo_CheckNegate(t *testing.T) {
	pt := testPoint(5)
	neg := runar.EcNegate(pt)
	expectedNegY := runar.EcPointY(neg)

	c := &ECDemo{Pt: pt}
	c.CheckNegate(expectedNegY)
}

func TestECDemo_CheckNegate_WrongY(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong negated y")
		}
	}()

	pt := testPoint(5)
	c := &ECDemo{Pt: pt}
	c.CheckNegate(0)
}

// ---------------------------------------------------------------------------
// checkNegateRoundtrip
// ---------------------------------------------------------------------------

func TestECDemo_CheckNegateRoundtrip(t *testing.T) {
	pt := testPoint(13)
	c := &ECDemo{Pt: pt}
	c.CheckNegateRoundtrip() // -(-P) = P, should not panic
}

// ---------------------------------------------------------------------------
// checkModReduce (ecModReduce)
// ---------------------------------------------------------------------------

func TestECDemo_CheckModReduce_Positive(t *testing.T) {
	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	// 17 % 5 = 2
	c.CheckModReduce(17, 5, 2)
}

func TestECDemo_CheckModReduce_Negative(t *testing.T) {
	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	// -3 mod 5 = 2 (non-negative reduction)
	c.CheckModReduce(-3, 5, 2)
}

func TestECDemo_CheckModReduce_WrongResult(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong mod-reduce result")
		}
	}()

	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	c.CheckModReduce(17, 5, 3) // 17 % 5 = 2, not 3
}

// ---------------------------------------------------------------------------
// checkEncodeCompressed (ecEncodeCompressed)
// ---------------------------------------------------------------------------

func TestECDemo_CheckEncodeCompressed(t *testing.T) {
	pt := testPoint(9)
	compressed := runar.EcEncodeCompressed(pt)

	c := &ECDemo{Pt: pt}
	c.CheckEncodeCompressed(compressed)
}

func TestECDemo_CheckEncodeCompressed_WrongBytes(t *testing.T) {
	defer func() {
		if r := recover(); r == nil {
			t.Fatal("expected assertion failure for wrong compressed encoding")
		}
	}()

	pt := testPoint(9)
	c := &ECDemo{Pt: pt}
	c.CheckEncodeCompressed(runar.ByteString("wrong"))
}

// ---------------------------------------------------------------------------
// checkMulIdentity
// ---------------------------------------------------------------------------

func TestECDemo_CheckMulIdentity(t *testing.T) {
	pt := testPoint(17)
	c := &ECDemo{Pt: pt}
	c.CheckMulIdentity() // 1 * P = P
}

// ---------------------------------------------------------------------------
// checkAddOnCurve
// ---------------------------------------------------------------------------

func TestECDemo_CheckAddOnCurve(t *testing.T) {
	pt := testPoint(11)
	other := testPoint(23)
	c := &ECDemo{Pt: pt}
	c.CheckAddOnCurve(other)
}

// ---------------------------------------------------------------------------
// checkMulGenOnCurve
// ---------------------------------------------------------------------------

func TestECDemo_CheckMulGenOnCurve(t *testing.T) {
	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	c.CheckMulGenOnCurve(42)
}

func TestECDemo_CheckMulGenOnCurve_LargeScalar(t *testing.T) {
	pt := testPoint(1)
	c := &ECDemo{Pt: pt}
	c.CheckMulGenOnCurve(999999)
}

// ---------------------------------------------------------------------------
// Compile check
// ---------------------------------------------------------------------------

func TestECDemo_Compile(t *testing.T) {
	if err := runar.CompileCheck("ECDemo.runar.go"); err != nil {
		t.Fatalf("Runar compile check failed: %v", err)
	}
}
