"""Cross-tier interop test for the signed-envelope wire protocol.

Loads `conformance/sdk-envelope/fixtures.json` (generated by the TS reference)
and asserts:

  1. canonical_json produces byte-identical output for every input.
  2. verify_envelope returns ok=True on the valid envelope at verify_now_ms.
  3. verify_envelope returns the listed reason for every tampered envelope.

Any failure here is a cross-tier protocol divergence. See CLAUDE.md §"Seven
SDKs Must Stay in Sync".
"""

import json
import hashlib
import pathlib

import pytest

from runar.ecdsa import ecdsa_sign
from runar.sdk.envelope import (
    canonical_json,
    verify_envelope,
    SignedEnvelope,
    VerifyEnvelopeReason,
)

FIXTURE_PATH = pathlib.Path(__file__).resolve().parents[3] / "conformance" / "sdk-envelope" / "fixtures.json"


@pytest.fixture(scope="module")
def fixture() -> dict:
    return json.loads(FIXTURE_PATH.read_text())


def test_canonical_json_vectors(fixture: dict) -> None:
    for i, v in enumerate(fixture["canonical_json_vectors"]):
        got = canonical_json(v["input"])
        assert got == v["expected"], f"vector {i}: got {got!r}, want {v['expected']!r}"


def test_verify_valid_envelope(fixture: dict) -> None:
    env = SignedEnvelope.from_dict(fixture["valid_envelope"])
    r = verify_envelope(env, now_ms=fixture["verify_now_ms"])
    assert r.ok, f"expected ok=true; reason={r.reason}"


def test_verify_rejection_vectors(fixture: dict) -> None:
    for v in fixture["rejection_vectors"]:
        env = SignedEnvelope.from_dict(v["envelope"])
        r = verify_envelope(env, now_ms=fixture["verify_now_ms"])
        assert not r.ok, f"rejection {v['reason']!r} should not be OK"
        assert r.reason == VerifyEnvelopeReason(v["reason"]), (
            f"rejection {v['reason']!r}: got reason={r.reason}"
        )


def test_signing_vectors(fixture: dict) -> None:
    """GAP-064 cross-tier signing reproduction. Signing the SAME payload with
    the SAME key (priv=1) via RFC 6979 deterministic ECDSA (plain-SHA-256
    nonce, low-S) MUST yield the byte-identical DER signature the TS reference
    committed. ecdsa_sign signs the 32-byte digest directly.
    """
    alice_priv = 1
    vectors = fixture["signing_vectors"]
    assert vectors, "signing_vectors missing or empty"
    for v in vectors:
        vid = v.get("_vector_id", "?")
        # Drift guard: re-derive the canonical payload from data + lifetime.
        merged = {**v["data"], "nonce": v["nonce"], "expiresAt": v["expiresAt"]}
        payload = canonical_json(merged)
        assert payload == v["expected_payload"], f"vector {vid}: payload"

        digest = hashlib.sha256(payload.encode("utf-8")).digest()
        der = ecdsa_sign(alice_priv, digest).hex()
        assert der == v["expected_sig"], f"vector {vid}: signature divergence"


def test_canonical_json_rejection_vectors(fixture: dict) -> None:
    """RFC 8785 §3.2.2.2: canonical_json MUST reject malformed Unicode
    (lone surrogate). See audits/canonical-json-rfc8785-parity.md §3 rec 6 (D6).

    R-262: this used to assert ``pytest.raises(Exception)`` — ANY error. That
    passes for any reason at all, proven by neutering canonical_json to raise
    an unrelated ValueError on every input: the test stayed green. It now
    asserts the tier's specific error type AND a message discriminator, and
    pairs each vector with a control whose ONLY difference is that the
    surrogate is PAIRED, so a rejection can be attributed to the lone
    surrogate rather than to the harness's string construction or to a guard
    that rejects everything.
    """
    for v in fixture["canonical_json_rejection_vectors"]:
        vid = v.get("_vector_id", "?")
        key = v["input_object_key"]
        # Build the input string from UTF-16 code units so we don't rely on
        # the JSON parser's lone-surrogate handling (which diverges by tier).
        units = v["input_value_utf16_units"]
        bad_str = "".join(chr(u) for u in units)
        with pytest.raises(ValueError, match="lone surrogate") as exc:
            canonical_json({key: bad_str})
        assert "U+D800" in str(exc.value), f"{vid}: {exc.value}"

        # CONTROL: the same object, same key, same code path — the only change
        # is that U+D800 is now the HIGH half of a valid pair (U+1F600). It
        # must serialise, and byte-identically to every other tier.
        good = canonical_json({key: "\ud83d\ude00".encode("utf-16", "surrogatepass").decode("utf-16")})
        assert good == '{"' + key + '":"\U0001F600"}', f"{vid}: control produced {good!r}"


def test_payload_depth_vectors(fixture: dict) -> None:
    """R-260. verify_envelope must bound payload nesting ITSELF rather than
    inherit whatever cap the stock JSON library happens to impose, because
    that cap differs per tier (ruby 100, rust 127, ts/go/python/zig none,
    java a StackOverflowError whose threshold is the JVM's -Xss flag). All
    seven tiers enforce MAX_ENVELOPE_PAYLOAD_DEPTH on the payload TEXT, so the
    same bytes get the same VerifyEnvelopeReason everywhere.
    """
    vectors = fixture["depth_vectors"]
    assert vectors, "depth_vectors missing or empty"
    for v in vectors:
        vid = v.get("_vector_id", "?")
        env = SignedEnvelope.from_dict(v["envelope"])
        r = verify_envelope(env, now_ms=fixture["verify_now_ms"])
        if v["expect_ok"]:
            assert r.ok, f"{vid}: expected ok=True, got reason={r.reason}"
        else:
            assert not r.ok, f"{vid}: expected ok=False"
            assert r.reason == VerifyEnvelopeReason(v["reason"]), (
                f"{vid}: got reason={r.reason}, want {v['reason']}"
            )


def test_payload_depth_limit_matches_fixture(fixture: dict) -> None:
    """The bound is part of the wire contract, so the fixture pins it and
    every tier asserts its own constant against the fixture's number."""
    from runar.sdk.envelope import MAX_ENVELOPE_PAYLOAD_DEPTH

    assert fixture["payload_depth_limit"] == MAX_ENVELOPE_PAYLOAD_DEPTH


def test_clock_skew_vectors(fixture: dict) -> None:
    """R-261. An EXPLICIT clock skew of 0 must mean 0, not "not supplied".

    Six tiers already distinguished the two; Go conflated them and silently
    gave a caller asking for strict expiry a five-second replay window, and
    both Go and Java did the same with the now-override. A ``None`` in the
    vector means the caller supplies no value and the tier default applies --
    that is the control: an over-strict fix reddens on cs2/cs3, not cs1.
    """
    env = SignedEnvelope.from_dict(fixture["valid_envelope"])
    vectors = fixture["clock_skew_vectors"]
    assert vectors, "clock_skew_vectors missing or empty"
    for v in vectors:
        vid = v.get("_vector_id", "?")
        kwargs = {"now_ms": v["now_ms"]}
        if v["clock_skew_ms"] is not None:
            kwargs["clock_skew_ms"] = v["clock_skew_ms"]
        r = verify_envelope(env, **kwargs)
        if v["expect_ok"]:
            assert r.ok, f"{vid}: expected ok=True, got reason={r.reason}"
        else:
            assert not r.ok, f"{vid}: expected ok=False"
            assert r.reason == VerifyEnvelopeReason(v["reason"]), (
                f"{vid}: got reason={r.reason}, want {v['reason']}"
            )
