"""Cross-tier interop test for the signed-envelope wire protocol.

Loads `conformance/sdk-envelope/fixtures.json` (generated by the TS reference)
and asserts:

  1. canonical_json produces byte-identical output for every input.
  2. verify_envelope returns ok=True on the valid envelope at verify_now_ms.
  3. verify_envelope returns the listed reason for every tampered envelope.

Any failure here is a cross-tier protocol divergence. See CLAUDE.md §"Seven
SDKs Must Stay in Sync".
"""

import json
import pathlib

import pytest

from runar.sdk.envelope import (
    canonical_json,
    verify_envelope,
    SignedEnvelope,
    VerifyEnvelopeReason,
)

FIXTURE_PATH = pathlib.Path(__file__).resolve().parents[3] / "conformance" / "sdk-envelope" / "fixtures.json"


@pytest.fixture(scope="module")
def fixture() -> dict:
    return json.loads(FIXTURE_PATH.read_text())


def test_canonical_json_vectors(fixture: dict) -> None:
    for i, v in enumerate(fixture["canonical_json_vectors"]):
        got = canonical_json(v["input"])
        assert got == v["expected"], f"vector {i}: got {got!r}, want {v['expected']!r}"


def test_verify_valid_envelope(fixture: dict) -> None:
    env = SignedEnvelope.from_dict(fixture["valid_envelope"])
    r = verify_envelope(env, now_ms=fixture["verify_now_ms"])
    assert r.ok, f"expected ok=true; reason={r.reason}"


def test_verify_rejection_vectors(fixture: dict) -> None:
    for v in fixture["rejection_vectors"]:
        env = SignedEnvelope.from_dict(v["envelope"])
        r = verify_envelope(env, now_ms=fixture["verify_now_ms"])
        assert not r.ok, f"rejection {v['reason']!r} should not be OK"
        assert r.reason == VerifyEnvelopeReason(v["reason"]), (
            f"rejection {v['reason']!r}: got reason={r.reason}"
        )
