package runar.compiler.frontend;

import org.junit.jupiter.api.Test;
import runar.compiler.ir.ast.AssignmentStatement;
import runar.compiler.ir.ast.BigIntLiteral;
import runar.compiler.ir.ast.BinaryExpr;
import runar.compiler.ir.ast.CallExpr;
import runar.compiler.ir.ast.ContractNode;
import runar.compiler.ir.ast.DecrementExpr;
import runar.compiler.ir.ast.Expression;
import runar.compiler.ir.ast.ExpressionStatement;
import runar.compiler.ir.ast.Identifier;
import runar.compiler.ir.ast.IncrementExpr;
import runar.compiler.ir.ast.MemberExpr;
import runar.compiler.ir.ast.ParentClass;
import runar.compiler.ir.ast.PrimitiveType;
import runar.compiler.ir.ast.PrimitiveTypeName;
import runar.compiler.ir.ast.PropertyAccessExpr;
import runar.compiler.ir.ast.PropertyNode;
import runar.compiler.ir.ast.Visibility;

import java.math.BigInteger;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertInstanceOf;
import static org.junit.jupiter.api.Assertions.assertNotNull;
import static org.junit.jupiter.api.Assertions.assertNull;
import static org.junit.jupiter.api.Assertions.assertThrows;
import static org.junit.jupiter.api.Assertions.assertTrue;

class GoParserTest {

    private static final String P2PKH_SOURCE = """
        package contract

        import runar "github.com/icellan/runar/packages/runar-go"

        // P2PKH — Pay-to-Public-Key-Hash.
        type P2PKH struct {
        \trunar.SmartContract
        \tPubKeyHash runar.Addr `runar:"readonly"`
        }

        // Unlock verifies the pubKey hashes to the committed hash, then checks the signature.
        func (c *P2PKH) Unlock(sig runar.Sig, pubKey runar.PubKey) {
        \trunar.Assert(runar.Hash160(pubKey) == c.PubKeyHash)
        \trunar.Assert(runar.CheckSig(sig, pubKey))
        }
        """;

    private static final String COUNTER_SOURCE = """
        package contract

        import runar "github.com/icellan/runar/packages/runar-go"

        type Counter struct {
        \trunar.StatefulSmartContract
        \tCount runar.Bigint
        \tOwner runar.Addr `runar:"readonly"`
        }

        func (c *Counter) Increment() {
        \tc.Count++
        }

        func (c *Counter) Decrement() {
        \trunar.Assert(c.Count > 0)
        \tc.Count--
        }
        """;

    @Test
    void parsesP2pkhIntoExpectedContractShape() throws Exception {
        ContractNode c = GoParser.parse(P2PKH_SOURCE, "P2PKH.runar.go");
        assertEquals("P2PKH", c.name());
        assertEquals(ParentClass.SMART_CONTRACT, c.parentClass());
        assertEquals("P2PKH.runar.go", c.sourceFile());
        assertEquals(1, c.properties().size());

        PropertyNode pkh = c.properties().get(0);
        assertEquals("pubKeyHash", pkh.name());
        assertTrue(pkh.readonly());
        assertEquals(new PrimitiveType(PrimitiveTypeName.ADDR), pkh.type());
        assertNull(pkh.initializer());
    }

    @Test
    void parsesP2pkhAutoGeneratedConstructor() throws Exception {
        ContractNode c = GoParser.parse(P2PKH_SOURCE, "P2PKH.runar.go");
        var ctor = c.constructor();
        assertEquals("constructor", ctor.name());
        assertEquals(Visibility.PUBLIC, ctor.visibility());
        assertEquals(1, ctor.params().size());
        assertEquals("pubKeyHash", ctor.params().get(0).name());

        // Body: super(pubKeyHash); this.pubKeyHash = pubKeyHash;
        assertEquals(2, ctor.body().size());

        var superStmt = (ExpressionStatement) ctor.body().get(0);
        var superCall = (CallExpr) superStmt.expression();
        assertEquals("super", ((Identifier) superCall.callee()).name());
        assertEquals(1, superCall.args().size());
        assertEquals("pubKeyHash", ((Identifier) superCall.args().get(0)).name());

        var assign = (AssignmentStatement) ctor.body().get(1);
        assertEquals("pubKeyHash", ((PropertyAccessExpr) assign.target()).property());
        assertEquals("pubKeyHash", ((Identifier) assign.value()).name());
    }

    @Test
    void parsesP2pkhUnlockBuiltinCalls() throws Exception {
        ContractNode c = GoParser.parse(P2PKH_SOURCE, "P2PKH.runar.go");
        assertEquals(1, c.methods().size());
        var unlock = c.methods().get(0);
        assertEquals("unlock", unlock.name());
        assertEquals(Visibility.PUBLIC, unlock.visibility());
        assertEquals(2, unlock.params().size());
        assertEquals("sig", unlock.params().get(0).name());
        assertEquals(new PrimitiveType(PrimitiveTypeName.SIG), unlock.params().get(0).type());
        assertEquals("pubKey", unlock.params().get(1).name());
        assertEquals(new PrimitiveType(PrimitiveTypeName.PUB_KEY), unlock.params().get(1).type());

        assertEquals(2, unlock.body().size());

        // assert(hash160(pubKey) === this.pubKeyHash)
        var assertStmt = (ExpressionStatement) unlock.body().get(0);
        var assertCall = (CallExpr) assertStmt.expression();
        assertEquals("assert", ((Identifier) assertCall.callee()).name());
        var cmp = (BinaryExpr) assertCall.args().get(0);
        assertEquals(Expression.BinaryOp.EQ, cmp.op());
        var hashCall = (CallExpr) cmp.left();
        assertEquals("hash160", ((Identifier) hashCall.callee()).name());
        assertEquals("pubKey", ((Identifier) hashCall.args().get(0)).name());
        assertEquals("pubKeyHash", ((PropertyAccessExpr) cmp.right()).property());

        // assert(checkSig(sig, pubKey))
        var assertStmt2 = (ExpressionStatement) unlock.body().get(1);
        var assertCall2 = (CallExpr) assertStmt2.expression();
        assertEquals("assert", ((Identifier) assertCall2.callee()).name());
        var checkSig = (CallExpr) assertCall2.args().get(0);
        assertEquals("checkSig", ((Identifier) checkSig.callee()).name());
        assertEquals(2, checkSig.args().size());
    }

    @Test
    void parsesStatefulCounterWithReadonlyAndMutableFields() throws Exception {
        ContractNode c = GoParser.parse(COUNTER_SOURCE, "Counter.runar.go");
        assertEquals("Counter", c.name());
        assertEquals(ParentClass.STATEFUL_SMART_CONTRACT, c.parentClass());
        assertEquals(2, c.properties().size());

        PropertyNode count = c.properties().get(0);
        assertEquals("count", count.name());
        assertFalse(count.readonly(), "Count without struct tag must be mutable");
        assertEquals(new PrimitiveType(PrimitiveTypeName.BIGINT), count.type());

        PropertyNode owner = c.properties().get(1);
        assertEquals("owner", owner.name());
        assertTrue(owner.readonly(), "Owner with `runar:\"readonly\"` tag must be readonly");
        assertEquals(new PrimitiveType(PrimitiveTypeName.ADDR), owner.type());
    }

    @Test
    void parsesStatefulCounterMethods() throws Exception {
        ContractNode c = GoParser.parse(COUNTER_SOURCE, "Counter.runar.go");
        assertEquals(2, c.methods().size());

        var inc = c.methods().get(0);
        assertEquals("increment", inc.name());
        assertEquals(Visibility.PUBLIC, inc.visibility());
        assertEquals(1, inc.body().size());
        var incStmt = (ExpressionStatement) inc.body().get(0);
        var incExpr = (IncrementExpr) incStmt.expression();
        assertFalse(incExpr.prefix(), "c.Count++ is postfix");
        assertEquals("count", ((PropertyAccessExpr) incExpr.operand()).property());

        var dec = c.methods().get(1);
        assertEquals("decrement", dec.name());
        assertEquals(2, dec.body().size());
        // assert(this.count > 0)
        var assertStmt = (ExpressionStatement) dec.body().get(0);
        var assertCall = (CallExpr) assertStmt.expression();
        assertEquals("assert", ((Identifier) assertCall.callee()).name());
        var cmp = (BinaryExpr) assertCall.args().get(0);
        assertEquals(Expression.BinaryOp.GT, cmp.op());
        assertEquals("count", ((PropertyAccessExpr) cmp.left()).property());
        assertInstanceOf(BigIntLiteral.class, cmp.right());
        assertEquals(BigInteger.ZERO, ((BigIntLiteral) cmp.right()).value());
        // c.Count--
        var decStmt = (ExpressionStatement) dec.body().get(1);
        assertInstanceOf(DecrementExpr.class, decStmt.expression());
    }

    @Test
    void counterConstructorParamsExcludeInitialisedFields() throws Exception {
        ContractNode c = GoParser.parse(COUNTER_SOURCE, "Counter.runar.go");
        var ctor = c.constructor();
        // Both Count and Owner are uninitialised, so both are constructor params.
        assertEquals(2, ctor.params().size());
        assertEquals("count", ctor.params().get(0).name());
        assertEquals("owner", ctor.params().get(1).name());
    }

    @Test
    void initMethodIsFoldedIntoPropertyInitializers() throws Exception {
        String src = """
            package contract

            import runar "github.com/icellan/runar/packages/runar-go"

            type C struct {
            \trunar.StatefulSmartContract
            \tCount runar.Bigint
            \tFlag runar.Bool
            }

            func (c *C) init() {
            \tc.Count = 7
            \tc.Flag = true
            }
            """;
        ContractNode c = GoParser.parse(src, "C.runar.go");
        // init must not appear as a method.
        for (var m : c.methods()) {
            if ("init".equals(m.name())) {
                throw new AssertionError("init() should be folded into property initializers");
            }
        }
        var count = c.properties().get(0);
        assertNotNull(count.initializer(), "Count initializer must be set");
        assertEquals(BigInteger.valueOf(7), ((BigIntLiteral) count.initializer()).value());

        var flag = c.properties().get(1);
        assertNotNull(flag.initializer(), "Flag initializer must be set");

        // Constructor params must exclude initialised properties.
        assertEquals(0, c.constructor().params().size());
    }

    @Test
    void privateMethodLowercaseStaysPrivate() throws Exception {
        String src = """
            package contract

            import runar "github.com/icellan/runar/packages/runar-go"

            type C struct {
            \trunar.SmartContract
            \tA runar.Bigint `runar:"readonly"`
            }

            func (c *C) Public() {
            \tc.helper()
            }

            func (c *C) helper() {
            \trunar.Assert(c.A > 0)
            }
            """;
        ContractNode c = GoParser.parse(src, "C.runar.go");
        assertEquals(2, c.methods().size());
        var pub = c.methods().get(0);
        assertEquals("public", pub.name());
        assertEquals(Visibility.PUBLIC, pub.visibility());
        var helper = c.methods().get(1);
        assertEquals("helper", helper.name());
        assertEquals(Visibility.PRIVATE, helper.visibility());
    }

    @Test
    void runarDotByteStringLiteralIsHexEncoded() throws Exception {
        String src = """
            package contract

            import runar "github.com/icellan/runar/packages/runar-go"

            type C struct {
            \trunar.SmartContract
            \tMagic runar.ByteString `runar:"readonly"`
            }

            func (c *C) Check() {
            \trunar.Assert(c.Magic == runar.ByteString("\\xde\\xad\\xbe\\xef"))
            }
            """;
        ContractNode c = GoParser.parse(src, "C.runar.go");
        var stmt = (ExpressionStatement) c.methods().get(0).body().get(0);
        var assertCall = (CallExpr) stmt.expression();
        var cmp = (BinaryExpr) assertCall.args().get(0);
        var lit = (runar.compiler.ir.ast.ByteStringLiteral) cmp.right();
        assertEquals("deadbeef", lit.value());
    }

    @Test
    void rejectsSourceWithoutContractStruct() {
        String src = """
            package contract
            import runar "github.com/icellan/runar/packages/runar-go"
            // no struct that embeds SmartContract / StatefulSmartContract
            type Helper struct {
            \tX int64
            }
            """;
        GoParser.ParseException e = assertThrows(GoParser.ParseException.class,
            () -> GoParser.parse(src, "X.runar.go"));
        assertTrue(e.getMessage().contains("no Rúnar contract"),
            "expected missing-contract error; got: " + e.getMessage());
    }

    @Test
    void rejectsTruncatedStruct() {
        // Missing closing brace and beyond — recursive descent should bail with errors.
        String src = """
            package contract
            import runar "github.com/icellan/runar/packages/runar-go"

            type Bad struct {
            \trunar.SmartContract
            \tA runar.Addr
            """;
        // The parser reports diagnostics for the missing RBRACE and missing parent class
        // means no contract is produced -> ParseException.
        assertThrows(GoParser.ParseException.class,
            () -> GoParser.parse(src, "Bad.runar.go"));
    }

    @Test
    void parsesShortVarDeclAndAssignment() throws Exception {
        String src = """
            package contract

            import runar "github.com/icellan/runar/packages/runar-go"

            type C struct {
            \trunar.StatefulSmartContract
            \tCount runar.Bigint
            }

            func (c *C) Add(delta runar.Bigint) {
            \tnewVal := c.Count + delta
            \tc.Count = newVal
            }
            """;
        ContractNode c = GoParser.parse(src, "C.runar.go");
        var add = c.methods().get(0);
        assertEquals("add", add.name());
        assertEquals(2, add.body().size());

        var decl = (runar.compiler.ir.ast.VariableDeclStatement) add.body().get(0);
        assertEquals("newVal", decl.name());
        var rhs = (BinaryExpr) decl.init();
        assertEquals(Expression.BinaryOp.ADD, rhs.op());
        assertEquals("count", ((PropertyAccessExpr) rhs.left()).property());
        assertEquals("delta", ((Identifier) rhs.right()).name());

        var assign = (AssignmentStatement) add.body().get(1);
        assertEquals("count", ((PropertyAccessExpr) assign.target()).property());
        assertEquals("newVal", ((Identifier) assign.value()).name());
    }

    @Test
    void parsesIfElseAndForLoop() throws Exception {
        String src = """
            package contract

            import runar "github.com/icellan/runar/packages/runar-go"

            type C struct {
            \trunar.SmartContract
            \tA runar.Bigint `runar:"readonly"`
            }

            func (c *C) Choose(x runar.Bigint) {
            \tif x > 0 {
            \t\trunar.Assert(true)
            \t} else {
            \t\trunar.Assert(false)
            \t}
            \tfor i := int64(0); i < 3; i++ {
            \t\trunar.Assert(true)
            \t}
            }
            """;
        ContractNode c = GoParser.parse(src, "C.runar.go");
        var m = c.methods().get(0);
        assertEquals(2, m.body().size());
        assertInstanceOf(runar.compiler.ir.ast.IfStatement.class, m.body().get(0));
        var forStmt = (runar.compiler.ir.ast.ForStatement) m.body().get(1);
        assertNotNull(forStmt.init());
        assertNotNull(forStmt.condition());
        assertNotNull(forStmt.update());
        assertInstanceOf(IncrementExpr.class,
            ((ExpressionStatement) forStmt.update()).expression());
    }

    @Test
    void receiverDotMethodLowersToThisMethodCall() throws Exception {
        String src = """
            package contract

            import runar "github.com/icellan/runar/packages/runar-go"

            type C struct {
            \trunar.SmartContract
            \tA runar.Bigint `runar:"readonly"`
            }

            func (c *C) Public() {
            \tc.helper(c.A)
            }

            func (c *C) helper(x runar.Bigint) {
            \trunar.Assert(x > 0)
            }
            """;
        ContractNode c = GoParser.parse(src, "C.runar.go");
        var pub = c.methods().get(0);
        var stmt = (ExpressionStatement) pub.body().get(0);
        var call = (CallExpr) stmt.expression();
        var callee = (MemberExpr) call.callee();
        assertEquals("helper", callee.property());
        assertEquals("this", ((Identifier) callee.object()).name());
        // Argument is this.a (PropertyAccessExpr), since c.A on the receiver lowers to that.
        assertEquals("a", ((PropertyAccessExpr) call.args().get(0)).property());
    }
}
