package runar.compiler.frontend;

import java.math.BigInteger;
import org.junit.jupiter.api.Test;
import runar.compiler.ir.ast.AssignmentStatement;
import runar.compiler.ir.ast.BigIntLiteral;
import runar.compiler.ir.ast.BinaryExpr;
import runar.compiler.ir.ast.CallExpr;
import runar.compiler.ir.ast.ContractNode;
import runar.compiler.ir.ast.Expression;
import runar.compiler.ir.ast.ExpressionStatement;
import runar.compiler.ir.ast.Identifier;
import runar.compiler.ir.ast.MemberExpr;
import runar.compiler.ir.ast.ParentClass;
import runar.compiler.ir.ast.PrimitiveType;
import runar.compiler.ir.ast.PrimitiveTypeName;
import runar.compiler.ir.ast.PropertyAccessExpr;
import runar.compiler.ir.ast.PropertyNode;
import runar.compiler.ir.ast.Visibility;

import static org.junit.jupiter.api.Assertions.*;

class RustParserTest {

    private static final String P2PKH_SOURCE = """
        use runar::prelude::*;

        #[runar::contract]
        pub struct P2PKH {
            #[readonly]
            pub pub_key_hash: Addr,
        }

        #[runar::methods(P2PKH)]
        impl P2PKH {
            #[public]
            pub fn unlock(&self, sig: &Sig, pub_key: &PubKey) {
                assert!(hash160(pub_key) == self.pub_key_hash);
                assert!(check_sig(sig, pub_key));
            }
        }
        """;

    private static final String COUNTER_SOURCE = """
        use runar::prelude::*;

        #[runar::contract]
        pub struct Counter {
            pub count: Bigint,
        }

        #[runar::methods(Counter)]
        impl Counter {
            #[public]
            pub fn increment(&mut self) {
                self.count += 1;
            }

            #[public]
            pub fn decrement(&mut self) {
                assert!(self.count > 0);
                self.count -= 1;
            }
        }
        """;

    @Test
    void parsesP2pkhContractShape() throws Exception {
        ContractNode c = RustParser.parse(P2PKH_SOURCE, "P2PKH.runar.rs");
        assertEquals("P2PKH", c.name());
        assertEquals(ParentClass.SMART_CONTRACT, c.parentClass());
        assertEquals("P2PKH.runar.rs", c.sourceFile());
        assertEquals(1, c.properties().size());
        PropertyNode pkh = c.properties().get(0);
        assertEquals("pubKeyHash", pkh.name());
        assertTrue(pkh.readonly());
        assertEquals(new PrimitiveType(PrimitiveTypeName.ADDR), pkh.type());
        assertNull(pkh.initializer());
    }

    @Test
    void parsesAutoGeneratedConstructor() throws Exception {
        ContractNode c = RustParser.parse(P2PKH_SOURCE, "P2PKH.runar.rs");
        var ctor = c.constructor();
        assertEquals("constructor", ctor.name());
        assertEquals(Visibility.PUBLIC, ctor.visibility());
        assertEquals(1, ctor.params().size());
        assertEquals("pubKeyHash", ctor.params().get(0).name());

        // body[0]: super(pubKeyHash)
        var superStmt = (ExpressionStatement) ctor.body().get(0);
        var superCall = (CallExpr) superStmt.expression();
        assertEquals("super", ((Identifier) superCall.callee()).name());
        assertEquals(1, superCall.args().size());
        assertEquals("pubKeyHash", ((Identifier) superCall.args().get(0)).name());

        // body[1]: this.pubKeyHash = pubKeyHash
        var assign = (AssignmentStatement) ctor.body().get(1);
        assertEquals("pubKeyHash", ((PropertyAccessExpr) assign.target()).property());
        assertEquals("pubKeyHash", ((Identifier) assign.value()).name());
    }

    @Test
    void parsesUnlockMethodWithBuiltins() throws Exception {
        ContractNode c = RustParser.parse(P2PKH_SOURCE, "P2PKH.runar.rs");
        assertEquals(1, c.methods().size());
        var unlock = c.methods().get(0);
        assertEquals("unlock", unlock.name());
        assertEquals(Visibility.PUBLIC, unlock.visibility());
        assertEquals(2, unlock.params().size());
        assertEquals("sig", unlock.params().get(0).name());
        assertEquals("pubKey", unlock.params().get(1).name());
        assertEquals(new PrimitiveType(PrimitiveTypeName.SIG), unlock.params().get(0).type());
        assertEquals(new PrimitiveType(PrimitiveTypeName.PUB_KEY), unlock.params().get(1).type());

        assertEquals(2, unlock.body().size());

        // assert!(hash160(pub_key) == self.pub_key_hash)
        // → assert(hash160(pubKey) === self.pubKeyHash)
        var firstStmt = (ExpressionStatement) unlock.body().get(0);
        var assertCall = (CallExpr) firstStmt.expression();
        assertEquals("assert", ((Identifier) assertCall.callee()).name());
        assertEquals(1, assertCall.args().size());
        var cmp = (BinaryExpr) assertCall.args().get(0);
        assertEquals(Expression.BinaryOp.EQ, cmp.op());
        var hashCall = (CallExpr) cmp.left();
        assertEquals("hash160", ((Identifier) hashCall.callee()).name());
        assertEquals(1, hashCall.args().size());
        assertEquals("pubKey", ((Identifier) hashCall.args().get(0)).name());
        assertEquals("pubKeyHash", ((PropertyAccessExpr) cmp.right()).property());

        // assert!(check_sig(sig, pub_key))
        var secondStmt = (ExpressionStatement) unlock.body().get(1);
        var secondAssertCall = (CallExpr) secondStmt.expression();
        var checkSigCall = (CallExpr) secondAssertCall.args().get(0);
        // snake_case check_sig must be remapped to checkSig.
        assertEquals("checkSig", ((Identifier) checkSigCall.callee()).name());
    }

    @Test
    void parsesStatefulCounterAsStatefulContract() throws Exception {
        ContractNode c = RustParser.parse(COUNTER_SOURCE, "Counter.runar.rs");
        assertEquals("Counter", c.name());
        // No #[readonly] on `count` => promoted to StatefulSmartContract.
        assertEquals(ParentClass.STATEFUL_SMART_CONTRACT, c.parentClass());
        assertEquals(1, c.properties().size());
        var count = c.properties().get(0);
        assertEquals("count", count.name());
        assertFalse(count.readonly());
        assertEquals(new PrimitiveType(PrimitiveTypeName.BIGINT), count.type());
    }

    @Test
    void parsesCompoundAssignmentsOnSelfFields() throws Exception {
        ContractNode c = RustParser.parse(COUNTER_SOURCE, "Counter.runar.rs");
        assertEquals(2, c.methods().size());

        var increment = c.methods().get(0);
        assertEquals("increment", increment.name());
        assertEquals(1, increment.body().size());
        var assign = (AssignmentStatement) increment.body().get(0);
        assertEquals("count", ((PropertyAccessExpr) assign.target()).property());
        var rhs = (BinaryExpr) assign.value();
        assertEquals(Expression.BinaryOp.ADD, rhs.op());
        // LHS is the self.count target, RHS is BigIntLiteral(1).
        assertEquals("count", ((PropertyAccessExpr) rhs.left()).property());
        assertEquals(BigInteger.ONE, ((BigIntLiteral) rhs.right()).value());

        var decrement = c.methods().get(1);
        assertEquals("decrement", decrement.name());
        // assert!(self.count > 0); self.count -= 1;
        assertEquals(2, decrement.body().size());
        var assertStmt = (ExpressionStatement) decrement.body().get(0);
        var assertCall = (CallExpr) assertStmt.expression();
        var gt = (BinaryExpr) assertCall.args().get(0);
        assertEquals(Expression.BinaryOp.GT, gt.op());
        assertEquals("count", ((PropertyAccessExpr) gt.left()).property());

        var subAssign = (AssignmentStatement) decrement.body().get(1);
        var subRhs = (BinaryExpr) subAssign.value();
        assertEquals(Expression.BinaryOp.SUB, subRhs.op());
    }

    @Test
    void mapsRustPrimitiveTypesToRunarBigint() throws Exception {
        String src = """
            #[runar::contract]
            pub struct C {
                #[readonly]
                pub a: i64,
                #[readonly]
                pub b: u64,
                #[readonly]
                pub c: i128,
                #[readonly]
                pub d: bool,
            }

            #[runar::methods(C)]
            impl C {}
            """;
        ContractNode c = RustParser.parse(src, "C.runar.rs");
        assertEquals(4, c.properties().size());
        assertEquals(new PrimitiveType(PrimitiveTypeName.BIGINT), c.properties().get(0).type());
        assertEquals(new PrimitiveType(PrimitiveTypeName.BIGINT), c.properties().get(1).type());
        assertEquals(new PrimitiveType(PrimitiveTypeName.BIGINT), c.properties().get(2).type());
        assertEquals(new PrimitiveType(PrimitiveTypeName.BOOLEAN), c.properties().get(3).type());
    }

    @Test
    void recognisesStatefulContractAttribute() throws Exception {
        String src = """
            #[runar::stateful_contract]
            pub struct S {
                #[readonly]
                pub owner: PubKey,
                pub seq: i64,
            }

            #[runar::methods(S)]
            impl S {}
            """;
        ContractNode c = RustParser.parse(src, "S.runar.rs");
        assertEquals(ParentClass.STATEFUL_SMART_CONTRACT, c.parentClass());
        assertEquals(2, c.properties().size());
        assertTrue(c.properties().get(0).readonly());
        assertFalse(c.properties().get(1).readonly());
    }

    @Test
    void extractsInitMethodAsPropertyInitializer() throws Exception {
        String src = """
            #[runar::contract]
            pub struct C {
                pub count: i64,
            }

            #[runar::methods(C)]
            impl C {
                fn init() {
                    self.count = 7;
                }
            }
            """;
        ContractNode c = RustParser.parse(src, "C.runar.rs");
        assertEquals(1, c.properties().size());
        var p = c.properties().get(0);
        assertNotNull(p.initializer(), "count should carry initializer from init()");
        assertEquals(BigInteger.valueOf(7), ((BigIntLiteral) p.initializer()).value());
        // init() must not appear as a regular method.
        assertTrue(c.methods().isEmpty(), "init() should be consumed");
        // Auto-generated constructor should have no params (count has initializer).
        assertEquals(0, c.constructor().params().size());
    }

    @Test
    void parsesForRangeLoopAsForStatement() throws Exception {
        String src = """
            #[runar::contract]
            pub struct C {
                #[readonly]
                pub n: i64,
            }

            #[runar::methods(C)]
            impl C {
                #[public]
                pub fn run(&self) {
                    for i in 0..10 {
                        assert!(i < 10);
                    }
                }
            }
            """;
        ContractNode c = RustParser.parse(src, "C.runar.rs");
        var run = c.methods().get(0);
        assertEquals(1, run.body().size());
        assertInstanceOf(runar.compiler.ir.ast.ForStatement.class, run.body().get(0));
        var forStmt = (runar.compiler.ir.ast.ForStatement) run.body().get(0);
        assertEquals("i", forStmt.init().name());
        assertEquals(BigInteger.ZERO, ((BigIntLiteral) forStmt.init().init()).value());
        var cond = (BinaryExpr) forStmt.condition();
        assertEquals(Expression.BinaryOp.LT, cond.op());
    }

    @Test
    void stripsCloneCalls() throws Exception {
        String src = """
            #[runar::contract]
            pub struct C {
                #[readonly]
                pub data: ByteString,
            }

            #[runar::methods(C)]
            impl C {
                #[public]
                pub fn check(&self) {
                    let x = self.data.clone();
                    assert!(x == self.data);
                }
            }
            """;
        ContractNode c = RustParser.parse(src, "C.runar.rs");
        var check = c.methods().get(0);
        var letStmt = (runar.compiler.ir.ast.VariableDeclStatement) check.body().get(0);
        // `self.data.clone()` should collapse to `self.data` (PropertyAccessExpr).
        assertInstanceOf(PropertyAccessExpr.class, letStmt.init());
        assertEquals("data", ((PropertyAccessExpr) letStmt.init()).property());
    }

    @Test
    void lowersAssertEqMacro() throws Exception {
        String src = """
            #[runar::contract]
            pub struct C {
                #[readonly]
                pub a: i64,
            }

            #[runar::methods(C)]
            impl C {
                #[public]
                pub fn check(&self, b: i64) {
                    assert_eq!(self.a, b);
                }
            }
            """;
        ContractNode c = RustParser.parse(src, "C.runar.rs");
        var check = c.methods().get(0);
        var stmt = (ExpressionStatement) check.body().get(0);
        var call = (CallExpr) stmt.expression();
        assertEquals("assert", ((Identifier) call.callee()).name());
        var cmp = (BinaryExpr) call.args().get(0);
        assertEquals(Expression.BinaryOp.EQ, cmp.op());
    }

    @Test
    void parsesIfElseStatement() throws Exception {
        String src = """
            #[runar::contract]
            pub struct C {
                #[readonly]
                pub a: i64,
            }

            #[runar::methods(C)]
            impl C {
                #[public]
                pub fn pick(&self, b: i64) {
                    if self.a > b {
                        assert!(true);
                    } else {
                        assert!(false);
                    }
                }
            }
            """;
        ContractNode c = RustParser.parse(src, "C.runar.rs");
        var pick = c.methods().get(0);
        var ifStmt = (runar.compiler.ir.ast.IfStatement) pick.body().get(0);
        assertNotNull(ifStmt.elseBody());
        assertEquals(1, ifStmt.thenBody().size());
        assertEquals(1, ifStmt.elseBody().size());
    }

    @Test
    void rejectsSourceWithoutContractStruct() {
        String src = "fn nope() {}";
        RustParser.ParseException e = assertThrows(
            RustParser.ParseException.class,
            () -> RustParser.parse(src, "nope.runar.rs")
        );
        assertTrue(e.getMessage().contains("No Runar contract"));
    }

    @Test
    void reportsUnclosedBraceAsParseError() {
        // Unterminated impl block — `expect(TOK_RBRACE)` records a diagnostic.
        String src = """
            #[runar::contract]
            pub struct C { #[readonly] pub a: i64, }
            #[runar::methods(C)]
            impl C {
                #[public]
                pub fn run(&self) { assert!(true);
            """;
        assertThrows(RustParser.ParseException.class,
            () -> RustParser.parse(src, "C.runar.rs"));
    }
}
